const entrada = [
  { display: "Abadia dos Dourados", valueString: "abadiense" },
  { display: "Abaeté", valueString: "abaeteense" },
  { display: "Abre Campo", valueString: "abre-campense" },
  { display: "Acaiaca", valueString: "acaiaquense" },
  { display: "Açucena", valueString: "açucenense" },
  { display: "Água Boa", valueString: "água-boense" },
  { display: "Água Comprida", valueString: "água-compridense" },
  { display: "Aguanil", valueString: "aguanilense" },
  { display: "Águas Formosas", valueString: "águas-formosense" },
  { display: "Águas Vermelhas", valueString: "vermelhense, águas-vermelhense" },
  { display: "Aimorés", valueString: "aimoreense" },
  { display: "Aiuruoca", valueString: "aiuruocano, aiuruoquense" },
  { display: "Alagoa", valueString: "alagoense" },
  { display: "Albertina", valueString: "albertinense" },
  { display: "Além Paraíba", valueString: "além-paraibano, além-paraibense" },
  { display: "Alfenas", valueString: "alfenense" },
  { display: "Alfredo Vasconcelos", valueString: "vasconcelense" },
  { display: "Almenara", valueString: "almenarense" },
  { display: "Alpercata", valueString: "alpercatense" },
  { display: "Alpinópolis", valueString: "alpinopolense" },
  { display: "Alterosa", valueString: "alterosense" },
  { display: "Alto Caparaó", valueString: "alto-caparoense" },
  {
    display: "Alto Jequitibá",
    valueString: "jequitibaense, alto-jequitibaense",
  },
  { display: "Alto Rio Doce", valueString: "alto-rio-docense" },
  { display: "Alvarenga", valueString: "alvarenguense" },
  { display: "Alvinópolis", valueString: "alvinopolense" },
  { display: "Alvorada de Minas", valueString: "alvoradense" },
  { display: "Amparo da Serra", valueString: "amparo-serrano" },
  { display: "Andradas", valueString: "andradense" },
  { display: "Andrelândia", valueString: "andrelandense" },
  { display: "Angelândia", valueString: "angelandense" },
  { display: "Antônio Carlos", valueString: "antoniocarlense" },
  { display: "Antônio Dias", valueString: "Antônio-Diense" },
  { display: "Antônio Prado de Minas", valueString: "Pradense-De-Minas" },
  { display: "Araçaí", valueString: "araçaiense" },
  { display: "Aracitaba", valueString: "aracitabense, aracitabano" },
  { display: "Araçuaí", valueString: "araçuaiense ou araçuaiano" },
  { display: "Araguari", valueString: "araguarino" },
  { display: "Arantina", valueString: "arantinense" },
  { display: "Araponga", valueString: "araponguense" },
  { display: "Araporã", valueString: "araporense" },
  { display: "Arapuá", valueString: "arapuense" },
  { display: "Araújos", valueString: "araujense" },
  { display: "Araxá", valueString: "araxaense" },
  { display: "Arceburgo", valueString: "arceburguense" },
  { display: "Arcos", valueString: "arcoense" },
  { display: "Areado", valueString: "areadense" },
  { display: "Argirita", valueString: "argiritense" },
  { display: "Aricanduva", valueString: "aricanduvense" },
  { display: "Arinos", valueString: "arinense" },
  { display: "Astolfo Dutra", valueString: "astolfo-dutrense" },
  { display: "Ataléia", valueString: "ataleiense" },
  { display: "Augusto de Lima", valueString: "augusto-limense" },
  { display: "Baependi", valueString: "baependiano" },
  { display: "Baldim", valueString: "baldinense" },
  { display: "Bambuí", valueString: "bambuiense" },
  { display: "Bandeira", valueString: "bandeirense" },
  { display: "Bandeira do Sul", valueString: "sul-bandeirante" },
  { display: "Barão de Cocais", valueString: "cocaiense" },
  { display: "Barão de Monte Alto", valueString: "montealtense" },
  { display: "Barbacena", valueString: "barbacenense" },
  { display: "Barra Longa", valueString: "barra-longuense" },
  { display: "Barroso", valueString: "barrosense" },
  { display: "Bela Vista de Minas", valueString: "belavistano" },
  { display: "Belmiro Braga", valueString: "belmirense" },
  { display: "Belo Horizonte", valueString: "belo-horizontino, belorizontino" },
  { display: "Belo Oriente", valueString: "belorientino" },
  { display: "Belo Vale", valueString: "belovalense" },
  { display: "Berilo", valueString: "berilense" },
  { display: "Berizal", valueString: "berizalense" },
  { display: "Bertópolis", valueString: "bertopolense" },
  { display: "Betim", valueString: "betinense" },
  { display: "Bias Fortes", valueString: "biasfortense" },
  { display: "Bicas", valueString: "biquense" },
  { display: "Biquinhas", valueString: "biquinhense" },
  { display: "Boa Esperança", valueString: "esperancense, dorense" },
  { display: "Bocaina de Minas", valueString: "bocainense" },
  { display: "Bocaiuva", valueString: "bocaiuvense" },
  { display: "Bom Despacho", valueString: "bom-despachense" },
  { display: "Bom Jardim de Minas", valueString: "bonjardinense" },
  { display: "Bom Jesus da Penha", valueString: "bonjesuense" },
  { display: "Bom Jesus do Amparo", valueString: "bonjesuense" },
  { display: "Bom Jesus do Galho", valueString: "bonjesuense" },
  { display: "Bom Repouso", valueString: "bom-repousense" },
  { display: "Bom Sucesso", valueString: "bom-sucessense" },
  { display: "Bonfim", valueString: "bonfinense" },
  { display: "Bonfinópolis de Minas", valueString: "bonfinopolitano" },
  { display: "Bonito de Minas", valueString: "bonitense" },
  { display: "Borda da Mata", valueString: "borda-matense" },
  { display: "Botelhos", valueString: "botelhense" },
  { display: "Botumirim", valueString: "botumirinense" },
  { display: "Brás Pires", valueString: "braspirense" },
  { display: "Brasilândia de Minas", valueString: "brasilandense" },
  { display: "Brasília de Minas", valueString: "brasil-minense" },
  { display: "Brazópolis", valueString: "brazopolense" },
  { display: "Braúnas", valueString: "braunense" },
  { display: "Brumadinho", valueString: "brumadinense" },
  { display: "Bueno Brandão", valueString: "bueno-brandense" },
  { display: "Buenópolis", valueString: "buenopolense" },
  { display: "Bugre", valueString: "bugrense" },
  { display: "Buritis", valueString: "buritisense" },
  { display: "Buritizeiro", valueString: "buritizeirense" },
  { display: "Cabeceira Grande", valueString: "cabeceirense" },
  { display: "Cabo Verde", valueString: "cabo-verdense" },
  { display: "Cachoeira Dourada", valueString: "cachoeiro-douradense" },
  { display: "Cachoeira da Prata", valueString: "cachoeirense" },
  { display: "Cachoeira de Minas", valueString: "cachoeirense" },
  { display: "Cachoeira de Pajeú", valueString: "cachoeirense" },
  { display: "Caetanópolis", valueString: "caetanopolitano" },
  { display: "Caeté", valueString: "caeteense" },
  { display: "Caiana", valueString: "caianense" },
  { display: "Cajuri", valueString: "cajuriense" },
  { display: "Caldas", valueString: "caldense" },
  { display: "Camacho", valueString: "camachense" },
  { display: "Camanducaia", valueString: "camanducaiense" },
  { display: "Cambuí", valueString: "cambuiense" },
  { display: "Cambuquira", valueString: "cambuquirense" },
  { display: "Campanário", valueString: "campanarense" },
  { display: "Campanha", valueString: "campanhense" },
  { display: "Campestre", valueString: "campestrense" },
  { display: "Campina Verde", valueString: "campina-verdense" },
  { display: "Campo Belo", valueString: "campo-belense" },
  { display: "Campos Gerais", valueString: "campos-geraiense" },
  { display: "Cana Verde", valueString: "cana-verdense" },
  { display: "Campo Azul", valueString: "campoazulense" },
  { display: "Campo Belo", valueString: "campo-belense" },
  { display: "Campo Florido", valueString: "campo floridense" },
  { display: "Campo do Meio", valueString: "campo-meiense" },
  { display: "Campos Altos", valueString: "campos-altense" },
  { display: "Campos Gerais", valueString: "campos-geraiense" },
  { display: "Cana Verde", valueString: "canaverdense" },
  { display: "Canaã", valueString: "canaense" },
  { display: "Canápolis", valueString: "canapolino" },
  { display: "Candeias", valueString: "candeense" },
  { display: "Cantagalo", valueString: "cantagalense" },
  { display: "Caparaó", valueString: "caparoense" },
  { display: "Capela Nova", valueString: "capela-novense" },
  { display: "Capelinha", valueString: "capelinhense" },
  { display: "Capetinga", valueString: "capetinguense" },
  { display: "Capim Branco", valueString: "capimbranquense" },
  { display: "Capinópolis", valueString: "capinopolense" },
  { display: "Capitão Andrade", valueString: "capitão-andradense" },
  { display: "Capitão Enéas", valueString: "eneapolitano, capitão-eneense" },
  { display: "Capitólio", valueString: "capitolino" },
  { display: "Caputira", valueString: "caputirense" },
  { display: "Caraí", valueString: "caraiense" },
  { display: "Caranaíba", valueString: "caranaibense" },
  { display: "Carandaí", valueString: "carandaiense" },
  { display: "Carangola", valueString: "carangolense" },
  { display: "Caratinga", valueString: "caratinguense" },
  { display: "Carbonita", valueString: "carbonitense" },
  { display: "Careaçu", valueString: "careaçuense" },
  { display: "Carlos Chagas", valueString: "carlos-chaguense" },
  { display: "Carmésia", valueString: "carmesiano" },
  { display: "Carmo da Cachoeira", valueString: "cachoeirense" },
  { display: "Carmo da Mata", valueString: "carmense" },
  { display: "Carmo de Minas", valueString: "carmoense, carmense" },
  { display: "Carmo do Cajuru", valueString: "cajuruense" },
  { display: "Carmo do Paranaíba", valueString: "carmelitano, carmense" },
  { display: "Carmo do Rio Claro", valueString: "carmelitano" },
  { display: "Carmópolis de Minas", valueString: "carmopolitano" },
  { display: "Carneirinho", valueString: "carneirinhense" },
  { display: "Carrancas", valueString: "carranquense" },
  { display: "Carvalhópolis", valueString: "carvalhopolitano" },
  { display: "Carvalhos", valueString: "carvalhense" },
  { display: "Casa Grande", valueString: "casa-grandense" },
  { display: "Cascalho Rico", valueString: "cascalho-riquense" },
  { display: "Cássia", valueString: "cassiense" },
  { display: "Cataguases", valueString: "cataguasense" },
  { display: "Catas Altas da Noruega", valueString: "catas-altense" },
  { display: "Catas Altas", valueString: "catas-altense" },
  { display: "Catuji", valueString: "catujiense" },
  { display: "Catuti", valueString: "catutiense" },
  { display: "Caxambu", valueString: "caxambuense" },
  { display: "Cedro do Abaeté", valueString: "cedrense" },
  { display: "Central de Minas", valueString: "centralense" },
  { display: "Centralina", valueString: "centralinense" },
  { display: "Chácara", valueString: "chacarense" },
  { display: "Chalé", valueString: "chaleense" },
  { display: "Chapada Gaúcha", valueString: "chapadense" },
  { display: "Chapada do Norte", valueString: "chapadense" },
  { display: "Chiador", valueString: "chiadorense" },
  { display: "Cipotânea", valueString: "cipotaneano, cipotanense" },
  { display: "Claraval", valueString: "claravalense" },
  { display: "Claro dos Poções", valueString: "claro-pocense" },
  { display: "Cláudio", valueString: "claudiense" },
  { display: "Coimbra", valueString: "coimbrense" },
  { display: "Coluna", valueString: "colunense" },
  { display: "Comendador Gomes", valueString: "comendadorense" },
  { display: "Comercinho", valueString: "comercinhense" },
  { display: "Conceição da Aparecida", valueString: "aparecidense" },
  { display: "Conceição da Barra de Minas", valueString: "concepcionense" },
  { display: "Conceição das Alagoas", valueString: "garimpense" },
  { display: "Conceição das Pedras", valueString: "pedrense" },
  { display: "Conceição de Ipanema", valueString: "ipanemense" },
  { display: "Conceição do Mato Dentro", valueString: "conceicionense" },
  { display: "Conceição do Pará", valueString: "conceição-paraense" },
  { display: "Conceição do Rio Verde", valueString: "conceicionense" },
  { display: "Conceição dos Ouros", valueString: "ourense" },
  { display: "Cônego Marinho", valueString: "cônego marinhense" },
  { display: "Confins", valueString: "confinense" },
  { display: "Congonhal", valueString: "congonhalense" },
  { display: "Congonhas do Norte", valueString: "norte congonhense" },
  { display: "Congonhas", valueString: "congonhense" },
  { display: "Conquista", valueString: "conquistense" },
  { display: "Conselheiro Lafaiete", valueString: "lafaietense" },
  { display: "Conselheiro Pena", valueString: "conselheiro-penense" },
  { display: "Consolação", valueString: "consolense" },
  { display: "Contagem", valueString: "contagense" },
  { display: "Coqueiral", valueString: "coqueirense" },
  { display: "Coração de Jesus", valueString: "corjesuense" },
  { display: "Cordisburgo", valueString: "cordisburguense" },
  { display: "Cordislândia", valueString: "Cordislandense" },
  { display: "Corinto", valueString: "corintiano" },
  { display: "Coromandel", valueString: "coromandelense" },
  { display: "Coronel Fabriciano", valueString: "fabricianense" },
  { display: "Coronel Murta", valueString: "murtense" },
  { display: "Coronel Pacheco", valueString: "pachequense" },
  { display: "Coronel Xavier Chaves", valueString: "xavierense" },
  { display: "Córrego Danta", valueString: "córrego-dantense" },
  { display: "Córrego Fundo", valueString: "corregofundense" },
  { display: "Córrego Novo", valueString: "córrego-novense" },
  { display: "Córrego do Bom Jesus", valueString: "correguense" },
  { display: "Couto de Magalhães de Minas", valueString: "couto-magalhense" },
  { display: "Crisólita", valueString: "crisolitense" },
  { display: "Cristais", valueString: "cristalense" },
  { display: "Cristália", valueString: "cristalense" },
  { display: "Cristiano Otoni", valueString: "cristianense" },
  { display: "Cristina", valueString: "cristinense" },
  { display: "Crucilândia", valueString: "crucilandense, crucilandês" },
  { display: "Cruzeiro da Fortaleza", valueString: "cruzeirense" },
  { display: "Cruzília", valueString: "cruziliense" },
  { display: "Cuparaque", valueString: "cuparaquense" },
  { display: "Curral de Dentro", valueString: "curraldentense" },
  { display: "Curvelo", valueString: "curvelano, curvelense" },
  { display: "Datas", valueString: "datense" },
  { display: "Delfim Moreira", valueString: "delfinense" },
  { display: "Delfinópolis", valueString: "delfinopolitano" },
  { display: "Delta", valueString: "deltense" },
  { display: "Descoberto", valueString: "descobertense" },
  { display: "Desterro de Entre Rios", valueString: "desterrense" },
  { display: "Desterro do Melo", valueString: "melense" },
  { display: "Diamantina", valueString: "diamantinense" },
  { display: "Diogo de Vasconcelos", valueString: "vasconcelense" },
  { display: "Dionísio", valueString: "dionisiano" },
  { display: "Divinésia", valueString: "divinesiano" },
  { display: "Divino", valueString: "divinense" },
  { display: "Divino das Laranjeiras", valueString: "divinense" },
  { display: "Divinolândia de Minas", valueString: "divinolandense" },
  { display: "Divinópolis", valueString: "divinopolitano" },
  { display: "Divisa Alegre", valueString: "divisalegrense" },
  { display: "Divisa Nova", valueString: "divisa-novense" },
  { display: "Divisópolis", valueString: "divisopolense" },
  { display: "Dom Bosco", valueString: "dom-bosquense" },
  { display: "Dom Cavati", valueString: "dom-cavatiano" },
  { display: "Dom Joaquim", valueString: "dom-joaquinense" },
  { display: "Dom Silvério", valueString: "dom-silveriense" },
  { display: "Dom Viçoso", valueString: "dom-viçosense" },
  { display: "Dona Euzébia", valueString: "euzebense" },
  { display: "Dores de Campos", valueString: "dores-campista" },
  { display: "Dores de Guanhães", valueString: "dorense" },
  { display: "Dores do Indaiá– dorense" },
  { display: "Dores do Turvo", valueString: "dorense" },
  { display: "Doresópolis", valueString: "doresopolitano" },
  { display: "Douradoquara", valueString: "douradoquarense" },
  { display: "Durandé", valueString: "durandeense" },
  { display: "Elói Mendes", valueString: "elói-mendense" },
  { display: "Engenheiro Caldas", valueString: "engenheiro-caldense" },
  { display: "Engenheiro Navarro", valueString: "navarrense" },
  { display: "Entre Folhas", valueString: "entrefolhense" },
  { display: "Entre Rios de Minas", valueString: "entrerriano" },
  { display: "Ervália", valueString: "ervalense" },
  { display: "Esmeraldas", valueString: "esmeraldense" },
  { display: "Espera Feliz", valueString: "espera-felizense" },
  { display: "Espinosa", valueString: "espinosense" },
  { display: "Espírito Santo do Dourado", valueString: "douradense" },
  { display: "Estiva", valueString: "estivense" },
  { display: "Estrela Dalva", valueString: "estrela-dalvense" },
  { display: "Estrela do Indaiá", valueString: "estrelense" },
  { display: "Estrela do Sul", valueString: "estrela-sulense" },
  { display: "Eugenópolis", valueString: "eugenopolitano" },
  { display: "Ewbank da Câmara", valueString: "ewbanquense" },
  { display: "Extrema", valueString: "extremense" },
  { display: "Fama", valueString: "famense" },
  { display: "Faria Lemos", valueString: "farialemense" },
  { display: "Felício dos Santos", valueString: "felisantense" },
  { display: "Felisburgo", valueString: "felisburguense" },
  { display: "Felixlândia", valueString: "felixlandense" },
  { display: "Fernandes Tourinho", valueString: "fernandes-tourinhense" },
  { display: "Ferros", valueString: "ferrense" },
  { display: "Fervedouro", valueString: "fervedourense" },
  { display: "Florestal", valueString: "florestalense" },
  { display: "Formiga", valueString: "formiguense" },
  { display: "Formoso", valueString: "formosense" },
  { display: "Fortaleza de Minas", valueString: "fortalezense" },
  { display: "Fortuna de Minas", valueString: "fortunense" },
  { display: "Francisco Badaró", valueString: "badarosense" },
  { display: "Francisco Dumont", valueString: "franco-dumontense" },
  { display: "Francisco Sá", valueString: "brejeiro, franciscosaense" },
  { display: "Franciscópolis", valueString: "franciscópolitano" },
  { display: "Frei Gaspar", valueString: "frei-gasparense" },
  { display: "Frei Inocêncio", valueString: "frei inocenciano" },
  { display: "Frei Lagonegro", valueString: "frei lagonegrense" },
  { display: "Fronteira", valueString: "fronteirense" },
  { display: "Fronteira dos Vales", valueString: "vale fronteirense" },
  { display: "Fruta de Leite", valueString: "fruta de leitense" },
  { display: "Frutal", valueString: "frutalense" },
  { display: "Funilândia", valueString: "funilandense" },
  { display: "Galiléia", valueString: "galileense" },
  { display: "Gameleiras", valueString: "gameleirense" },
  { display: "Glaucilândia", valueString: "glaucilandense" },
  { display: "Goiabeira", valueString: "goiabeirense" },
  { display: "Goianá", valueString: "goianaense" },
  { display: "Gonçalves", valueString: "gonçalvense" },
  { display: "Gonzaga", valueString: "gonzaguense" },
  { display: "Gouveia", valueString: "gouveano" },
  { display: "Governador Valadares", valueString: "valadarense" },
  { display: "Grão Mogol", valueString: "grão-mogolense" },
  { display: "Grupiara", valueString: "grupiarense" },
  { display: "Guanhães", valueString: "guanhanense" },
  { display: "Guapé", valueString: "guapeense" },
  { display: "Guaraciaba", valueString: "guaraciabense" },
  { display: "Guaraciama", valueString: "guaraciamense" },
  { display: "Guaranésia", valueString: "guaranesiano" },
  { display: "Guarani", valueString: "guaraniense" },
  { display: "Guarará", valueString: "guararense" },
  { display: "Guarda-Mor", valueString: "guarda-morense" },
  { display: "Guaxupé", valueString: "guaxupeano" },
  { display: "Guidoval", valueString: "guidovalense" },
  { display: "Guimarânia", valueString: "guimaraniense" },
  { display: "Guiricema", valueString: "guiricemense" },
  { display: "Gurinhatã", valueString: "gurinhatanhense" },
  { display: "Heliodora", valueString: "heliodorense" },
  { display: "Iapu", valueString: "iapuense" },
  { display: "Ibertioga", valueString: "ibertiogano" },
  { display: "Ibiá", valueString: "ibiaense" },
  { display: "Ibiaí", valueString: "ibiaiense" },
  { display: "Ibiracatu", valueString: "ibiracatuense" },
  { display: "Ibiraci", valueString: "ibiraciense" },
  { display: "Ibirité", valueString: "ibiritense" },
  { display: "Ibitiúra de Minas", valueString: "ibitiurense" },
  { display: "Ibituruna", valueString: "ibiturunense" },
  { display: "Icaraí de Minas", valueString: "icaraiminense" },
  { display: "Igarapé", valueString: "igarapense" },
  { display: "Igaratinga", valueString: "igaratinguense" },
  { display: "Iguatama", valueString: "iguatamense" },
  { display: "Ijaci", valueString: "ijaciense" },
  { display: "Ilicínea", valueString: "ilicinense" },
  { display: "Imbé de Minas", valueString: "imbeense" },
  { display: "Inconfidentes", valueString: "inconfidentino" },
  { display: "Indaiabira", valueString: "indaiabirense" },
  { display: "Indianópolis", valueString: "indianopolense" },
  { display: "Inimutaba", valueString: "inimutabense" },
  { display: "Ingaí", valueString: "ingaiense" },
  { display: "Inhapim", valueString: "inhapinhense" },
  { display: "Inhaúma", valueString: "inhaumense" },
  { display: "Inimutaba", valueString: "inimutabense" },
  { display: "Ipaba", valueString: "ipabense" },
  { display: "Ipanema", valueString: "ipanemense" },
  { display: "Ipatinga", valueString: "ipatinguense" },
  { display: "Ipiaçu", valueString: "ipiaçuense" },
  { display: "Ipuiuna", valueString: "ipuiunense" },
  { display: "Iraí de Minas", valueString: "iraiense" },
  { display: "Itabira", valueString: "itabirano" },
  { display: "Itabirinha", valueString: "itabirense" },
  { display: "Itabirito", valueString: "itabiritense" },
  { display: "Itacambira", valueString: "itacambirano" },
  { display: "Itacarambi", valueString: "itacarambiense" },
  { display: "Itaguara", valueString: "itaguarense" },
  { display: "Itaipé", valueString: "itaipeense" },
  { display: "Itajubá", valueString: "itajubense" },
  { display: "Itamarandiba", valueString: "itamarandibano" },
  { display: "Itamarati de Minas", valueString: "itamaratiense" },
  { display: "Itambacuri", valueString: "itambacuriense" },
  { display: "Itambé do Mato Dentro", valueString: "itambeense" },
  { display: "Itamogi", valueString: "itamogiense" },
  { display: "Itamonte", valueString: "itamontense" },
  { display: "Itanhandu", valueString: "itanhanduense" },
  { display: "Itanhomi", valueString: "itanhomiense" },
  { display: "Itaobim", valueString: "itaobinhense" },
  { display: "Itapagipe", valueString: "itapagipense" },
  { display: "Itapecerica", valueString: "itapecericano" },
  { display: "Itapeva", valueString: "itapevense" },
  { display: "Itatiaiuçu", valueString: "itatiaiuçuense" },
  { display: "Itaú de Minas", valueString: "itauense" },
  { display: "Itaúna", valueString: "itaunense" },
  { display: "Itaverava", valueString: "itaveravense" },
  { display: "Itinga", valueString: "itinguense" },
  { display: "Itueta", valueString: "ituetano" },
  { display: "Ituiutaba", valueString: "ituiutabano, tejucano" },
  { display: "Itumirim", valueString: "itumirense" },
  { display: "Iturama", valueString: "ituramense" },
  { display: "Itutinga", valueString: "itutinguense" },
  { display: "Jaboticatubas", valueString: "jaboticatubense" },
  { display: "Jacinto", valueString: "jacintense" },
  { display: "Jacuí", valueString: "jacuiense" },
  { display: "Jacutinga", valueString: "jacutinguense" },
  { display: "Jaguaraçu", valueString: "jaguaraçuense" },
  { display: "Jaíba", valueString: "jaibense" },
  { display: "Jampruca", valueString: "jampruquense" },
  { display: "Janaúba", valueString: "janaubense" },
  { display: "Januária", valueString: "januarense" },
  { display: "Japaraíba", valueString: "japaraíbano" },
  { display: "Japonvar", valueString: "japonvarense" },
  { display: "Jeceaba", valueString: "jeceabense, jeceabano" },
  { display: "Jenipapo de Minas", valueString: "jenipapense" },
  { display: "Jequeri", valueString: "jequeriense" },
  { display: "Jequitaí", valueString: "jequitaiense" },
  { display: "Jequitibá", valueString: "jequitibaense" },
  { display: "Jequitinhonha", valueString: "jequitinhonhense" },
  { display: "Jesuânia", valueString: "jesuanense" },
  { display: "Joaíma", valueString: "joaimense" },
  { display: "Joanésia", valueString: "joanense" },
  { display: "João Monlevade", valueString: "monlevadense" },
  { display: "João Pinheiro", valueString: "pinheirense" },
  { display: "Joaquim Felício", valueString: "joaquim-feliciano" },
  { display: "Jordânia", valueString: "jordaniense" },
  { display: "José Gonçalves de Minas", valueString: "gonçalvense" },
  { display: "José Raydan", valueString: "raydaense" },
  { display: "Josenópolis", valueString: "josenopolense" },
  { display: "Juatuba", valueString: "juatubense" },
  {
    display: "Juiz de Fora",
    valueString: "juiz-forano, juiz-de-forano, juiz-forense",
  },
  { display: "Juramente", valueString: "juramentense" },
  { display: "Juruaia", valueString: "juruaiense" },
  { display: "Juvenília", valueString: "juveniliense" },
  { display: "Ladainha", valueString: "ladainhense" },
  { display: "Lagamar", valueString: "lagamarense" },
  { display: "Lagoa da Prata", valueString: "lagopratense" },
  { display: "Lagoa dos Patos", valueString: "lagoa-patense" },
  { display: "Lagoa Dourada", valueString: "lagoa-douradense" },
  { display: "Lagoa Formosa", valueString: "lagoense" },
  { display: "Lagoa Grande", valueString: "lagoa-grandense" },
  { display: "Lagoa Santa", valueString: "lagoa-santense" },
  { display: "Lajinha", valueString: "lajinhense" },
  { display: "Lambari", valueString: "lambariense" },
  { display: "Lamim", valueString: "laminense" },
  { display: "Laranjal", valueString: "laranjalense" },
  { display: "Lassance", valueString: "lassancense" },
  { display: "Lavras", valueString: "lavrense" },
  { display: "Leandro Ferreira", valueString: "leandrense" },
  { display: "Leme do Prado", valueString: "lemepradense, leme-pradense" },
  { display: "Leopoldina", valueString: "leopoldinense" },
  { display: "Liberdade", valueString: "libertense" },
  { display: "Lima Duarte", valueString: "limaduartino" },
  { display: "Limeira do Oeste", valueString: "limeirense" },
  { display: "Lontra", valueString: "lontrense" },
  { display: "Luisburgo", valueString: "luisburguense" },
  { display: "Luislândia", valueString: "luislandense" },
  { display: "Luminárias", valueString: "luminarense" },
  { display: "Luz", valueString: "luzense" },
  { display: "Machacalis", valueString: "machacaliense" },
  { display: "Machado", valueString: "machadense" },
  { display: "Madre de Deus de Minas", valueString: "madre-deuense" },
  { display: "Malacacheta", valueString: "malacachetense" },
  { display: "Mamonas", valueString: "mamonense" },
  { display: "Manga", valueString: "manguense" },
  { display: "Manhuaçu", valueString: "manhuaçuense" },
  { display: "Manhumirim", valueString: "manhumiriense" },
  { display: "Mantena", valueString: "mantenense" },
  { display: "Mar de Espanha", valueString: "mardespanhense" },
  { display: "Maravilhas", valueString: "maravilhense" },
  { display: "Maria da Fé", valueString: "mariense" },
  { display: "Mariana", valueString: "marianense" },
  { display: "Marilac", valueString: "marilaquense" },
  { display: "Mário Campos", valueString: "mariocampense" },
  { display: "Maripá de Minas", valueString: "maripaense" },
  { display: "Marliéria", valueString: "marlierense" },
  { display: "Marmelópolis", valueString: "marmelopolense" },
  { display: "Martinho Campos", valueString: "martinhocampense" },
  { display: "Martins Soares", valueString: "martinsoarense" },
  { display: "Mata Verde", valueString: "mataverdense" },
  { display: "Materlândia", valueString: "materlandense" },
  { display: "Mateus Leme", valueString: "mateus-lemense" },
  { display: "Mathias Lobato", valueString: "mathias-lobatense" },
  { display: "Matias Barbosa", valueString: "matiense , matias-barbosense" },
  { display: "Matias Cardoso", valueString: "matiense" },
  { display: "Matipó", valueString: "matipoense" },
  { display: "Mato Verde", valueString: "mato-verdense" },
  { display: "Matozinhos", valueString: "matozinhense" },
  { display: "Matutina", valueString: "matutinense" },
  { display: "Medeiros", valueString: "madeirense" },
  { display: "Medina", valueString: "medinense" },
  { display: "Mendes Pimentel", valueString: "pimentelense" },
  { display: "Mercês", valueString: "mercesano" },
  { display: "Mesquita", valueString: "mesquitense" },
  { display: "Minas Novas", valueString: "minas-novense" },
  { display: "Minduri", valueString: "minduriense" },
  { display: "Mirabela", valueString: "mirabelense" },
  { display: "Miradouro", valueString: "miradourense" },
  { display: "Miraí", valueString: "miraiense" },
  { display: "Miravânia", valueString: "miravaniense" },
  { display: "Moeda", valueString: "moedense" },
  { display: "Moema", valueString: "moemense" },
  { display: "Monjolos", valueString: "monjolense" },
  { display: "Monsenhor Paulo", valueString: "paulense" },
  { display: "Montalvânia", valueString: "montalvanense , cochanino" },
  { display: "Monte Alegre de Minas", valueString: "monte-alegrense" },
  { display: "Monte Azul", valueString: "monte-azulense" },
  { display: "Monte Belo", valueString: "montebelense" },
  { display: "Monte Carmelo", valueString: "carmelitano" },
  { display: "Monte Formoso", valueString: "monte formosense" },
  { display: "Monte Santo de Minas", valueString: "monte-santense" },
  { display: "Monte Sião", valueString: "monte-sionense" },
  { display: "Montes Claros", valueString: "montes-clarense" },
  { display: "Montezuma", valueString: "montezumense" },
  { display: "Morada Nova de Minas", valueString: "moradense" },
  { display: "Morro da Garça", valueString: "garcense" },
  { display: "Morro do Pilar", valueString: "morrense" },
  { display: "Munhoz", valueString: "munhozense" },
  { display: "Muriaé", valueString: "muriaense" },
  { display: "Mutum", valueString: "mutuense" },
  { display: "Muzambinho", valueString: "muzambense" },
  { display: "Nacip Raydan", valueString: "nacipense" },
  { display: "Nanuque", valueString: "nanuquense" },
  { display: "Naque", valueString: "naquense" },
  { display: "Natalândia", valueString: "natalandense" },
  { display: "Natércia", valueString: "naterciano" },
  { display: "Nazareno", valueString: "nazarenense" },
  { display: "Nepomuceno", valueString: "nepomucenense" },
  { display: "Ninheira", valueString: "ninheirense" },
  { display: "Nova Belém", valueString: "novabelense" },
  { display: "Nova Era", valueString: "nova-erense" },
  { display: "Nova Lima", valueString: "nova-limense" },
  { display: "Nova Módica", valueString: "novamodicano" },
  { display: "Nova Ponte", valueString: "novapontense" },
  { display: "Nova Porteirinha", valueString: "novaporteirinhense" },
  { display: "Nova Resende", valueString: "nova-resendense" },
  { display: "Nova Serrana", valueString: "nova-serranense" },
  { display: "Nova União", valueString: "nova-uniense" },
  { display: "Novo Cruzeiro", valueString: "neocruzeirense" },
  { display: "Novo Oriente de Minas", valueString: "novo orientense" },
  { display: "Novorizontino", valueString: "novorizontino" },
  { display: "Olaria", valueString: "Olariense" },
  { display: "Olhos-d'Água", valueString: "olhos-d'aguense" },
  { display: "Olímpio Noronha", valueString: "olímpio-noronhense" },
  { display: "Oliveira", valueString: "oliveirense" },
  { display: "Oliveira Fortes", valueString: "oliveira-fortense" },
  { display: "Onça de Pitangui", valueString: "oncense" },
  { display: "Oratórios", valueString: "oratoriense" },
  { display: "Orizânia", valueString: "orizanense" },
  { display: "Ouro Branco", valueString: "ouro-branquense" },
  { display: "Ouro Fino", valueString: "ourofinense" },
  { display: "Ouro Preto", valueString: "ouro-pretano" },
  { display: "Ouro Verde de Minas", valueString: "ouroverdense" },
  { display: "Padre Carvalho", valueString: "padre carvaliense" },
  { display: "Padre Paraíso", valueString: "padre paraisense" },
  { display: "Pai Pedro", valueString: "paipedrense" },
  { display: "Paineiras", valueString: "paineirense" },
  { display: "Pains", valueString: "painense" },
  { display: "Paiva", valueString: "paivense" },
  { display: "Palma", valueString: "palmense" },
  { display: "Palmópolis", valueString: "palmopolense" },
  { display: "Papagaios", valueString: "papagaiense" },
  { display: "Pará de Minas", valueString: "pará-minense" },
  { display: "Paracatu", valueString: "paracatuense, paracatulino" },
  { display: "Paraguaçu", valueString: "paraguaçuense" },
  { display: "Paraisópolis", valueString: "paraisopolense, paraisopolitano" },
  { display: "Paraopeba", valueString: "paraopebense" },
  { display: "Passa Quatro", valueString: "passa-quatrense" },
  { display: "Passa Tempo", valueString: "passatempense" },
  { display: "Passa Vinte", valueString: "passavintense" },
  { display: "Passabém", valueString: "passabenense" },
  { display: "Passos", valueString: "passense" },
  { display: "Patis", valueString: "patisense" },
  { display: "Patos de Minas", valueString: "patense ou patureba" },
  { display: "Patrocínio", valueString: "patrocinense" },
  { display: "Patrocínio do Muriaé", valueString: "patrocinense" },
  { display: "Paula Cândido", valueString: "paula-candidense" },
  { display: "Paulistas", valueString: "paulistano" },
  { display: "Pavão", valueString: "Pavonense" },
  { display: "Peçanha", valueString: "peçanhense" },
  { display: "Pedra Azul", valueString: "pedrazulense" },
  { display: "Pedra Dourada", valueString: "douradense" },
  { display: "Pedra Bonita", valueString: "pedra-bonitense" },
  { display: "Pedra do Anta", valueString: "antense" },
  { display: "Pedra do Indaiá", valueString: "indaiaense" },
  { display: "Pedra Dourada", valueString: "douradense" },
  { display: "Pedralva", valueString: "pedralvense" },
  { display: "Pedras de Maria da Cruz", valueString: "pedrense" },
  { display: "Pedrinópolis", valueString: "pedrinopolense" },
  { display: "Pedro Leopoldo", valueString: "pedro-leopoldense" },
  { display: "Pedro Teixeira", valueString: "pedro-teixerense" },
  { display: "Pequeri", valueString: "pequeriense" },
  { display: "Pequi", valueString: "pequiense" },
  { display: "Perdigão", valueString: "perdigonense, perdiguense" },
  { display: "Perdizes", valueString: "perdizense" },
  { display: "Perdões", valueString: "perdoense" },
  { display: "Periquito", valueString: "periquitense" },
  { display: "Pescador", valueString: "pescadorense" },
  { display: "Piau", valueString: "piauense" },
  { display: "Piedade de Caratinga", valueString: "piedade-caratinguense" },
  { display: "Piedade de Ponte Nova", valueString: "piedadense" },
  { display: "Piedade do Rio Grande", valueString: "piedense" },
  { display: "Piedade dos Gerais", valueString: "piedadense" },
  { display: "Pimenta", valueString: "pimentense" },
  { display: "Pingo-d'Água", valueString: "pingodaguense" },
  { display: "Pintópolis", valueString: "pintopolense , pintopolitano" },
  { display: "Piracema", valueString: "piracemense" },
  { display: "Pirajuba", valueString: "pirajubense" },
  { display: "Piranga", valueString: "piranguense" },
  { display: "Piranguçu", valueString: "piranguçuense" },
  { display: "Piranguinho", valueString: "piranguinhense" },
  { display: "Pirapetinga", valueString: "pirapetinguense" },
  { display: "Pirapora", valueString: "piraporense" },
  { display: "Piraúba", valueString: "piraubense, piraubano(a)" },
  { display: "Pitangui", valueString: "pitanguiense" },
  { display: "Piumhi", valueString: "piumhiense [2]" },
  { display: "Planura", valueString: "planurense" },
  { display: "Poço Fundo", valueString: "poço-fundense" },
  { display: "Poços de Caldas", valueString: "poços-caldense" },
  { display: "Pocrane", valueString: "pocranense" },
  { display: "Pompéu", valueString: "pompeano" },
  { display: "Ponte Nova", valueString: "ponte-novense" },
  { display: "Ponto Chique", valueString: "ponto-chiquense" },
  { display: "Ponto dos Volantes", valueString: "ponto-volantense" },
  { display: "Porteirinha", valueString: "porteirinhense" },
  { display: "Porto Firme", valueString: "portofirmense" },
  { display: "Poté", valueString: "poteense" },
  { display: "Pouso Alegre", valueString: "pouso-alegrense" },
  { display: "Pouso Alto", valueString: "pouso-altense" },
  { display: "Prados", valueString: "pradense" },
  { display: "Prata", valueString: "pratense" },
  { display: "Pratápolis", valueString: "pratapolense" },
  { display: "Pratinha", valueString: "pratinhense" },
  { display: "Presidente Bernardes", valueString: "bernardense" },
  {
    display: "Presidente Juscelino",
    valueString: "juscelinense , presidente-juscilinense",
  },
  { display: "Presidente Kubitschek", valueString: "kubitschekense" },
  { display: "Presidente Olegário", valueString: "olegariense" },
  { display: "Prudente de Morais", valueString: "prudentino" },
  { display: "Quartel Geral", valueString: "quartelense" },
  { display: "Queluzito", valueString: "queluzitense" },
  { display: "Raposos", valueString: "raposense" },
  { display: "Raul Soares", valueString: "raul-soarense" },
  { display: "Recreio", valueString: "recreense" },
  { display: "Reduto", valueString: "Redutense" },
  { display: "Resende Costa", valueString: "resende-costense" },
  { display: "Resplendor", valueString: "resplendorense" },
  { display: "Ressaquinha", valueString: "ressaquinhense" },
  { display: "Riachinho", valueString: "riachinhense" },
  { display: "Riacho dos Machados", valueString: "riacho machadense" },
  { display: "Ribeirão das Neves", valueString: "nevense" },
  { display: "Ribeirão Vermelho", valueString: "ribeirense" },
  { display: "Rio Acima", valueString: "rioacimense" },
  { display: "Rio Casca", valueString: "rio-casquense" },
  { display: "Rio do Prado", valueString: "riopradense" },
  { display: "Rio Doce", valueString: "rio-docense" },
  { display: "Rio Espera", valueString: "rioesperense" },
  { display: "Rio Manso", valueString: "rio-mansense" },
  { display: "Rio Novo", valueString: "rio-novense" },
  { display: "Rio Paranaíba", valueString: "rio-paranaibano" },
  { display: "Rio Pardo de Minas", valueString: "rio-pardense" },
  { display: "Rio Piracicaba", valueString: "piracicabense" },
  { display: "Rio Pomba", valueString: "rio-pombense" },
  { display: "Rio Preto", valueString: "riopretano" },
  { display: "Rio Vermelho", valueString: "rio-vermelhense" },
  { display: "Ritápolis", valueString: "ritapolitano" },
  { display: "Rochedo de Minas", valueString: "rochedense" },
  { display: "Rodeiro", valueString: "rodeirense" },
  { display: "Romaria", valueString: "romariense" },
  { display: "Rosário da Limeira", valueString: "limeirense" },
  { display: "Rubelita", valueString: "rubelitense" },
  { display: "Rubim", valueString: "rubinense" },
  { display: "Sabará", valueString: "sabarense" },
  { display: "Sabinópolis", valueString: "sabinopolense" },
  { display: "Sacramento", valueString: "sacramentano" },
  { display: "Salinas", valueString: "salinense" },
  { display: "Salto da Divisa", valueString: "saltense" },
  { display: "Santa Bárbara", valueString: "santa-barbarense" },
  { display: "Santa Bárbara do Leste", valueString: "santabarbarense" },
  { display: "Santa Bárbara do Monte Verde", valueString: "barbarense" },
  { display: "Santa Bárbara do Tugúrio", valueString: "tuguriense" },
  { display: "Santa Cruz de Minas", valueString: "santacruzense" },
  { display: "Santa Cruz de Salinas", valueString: "santacruzense" },
  { display: "Santa Cruz do Escalvado", valueString: "santa-cruzense" },
  { display: "Santa Efigênia de Minas", valueString: "santa-efigense" },
  { display: "Santa Fé de Minas", valueString: "santa-feense" },
  { display: "Santa Helena de Minas", valueString: "santa-helenense" },
  { display: "Santa Juliana", valueString: "santa-julianense" },
  { display: "Santa Luzia", valueString: "luziense" },
  { display: "Santa Margarida", valueString: "margaridense" },
  { display: "Santa Maria de Itabira", valueString: "santamariense" },
  { display: "Santa Maria do Salto", valueString: "santa-mariense" },
  {
    display: "Santa Maria do Suaçuí",
    valueString: "santa-mariense , suaçuiense",
  },
  { display: "Santa Rita de Caldas", valueString: "santa-ritense" },
  { display: "Santa Rita de Ibitipoca", valueString: "santa-ritense" },
  { display: "Santa Rita de Jacutinga", valueString: "santa-ritense" },
  { display: "Santa Rita de Minas", valueString: "santa-ritense" },
  { display: "Santa Rita do Itueto", valueString: "santaritense" },
  { display: "Santa Rita do Sapucaí", valueString: "santa-ritense" },
  { display: "Santa Rosa da Serra", valueString: "rosaserrense" },
  { display: "Santa Vitória", valueString: "santa-vitoriense" },
  { display: "Santana da Vargem", valueString: "vargense" },
  { display: "Santana de Cataguases", valueString: "santanense" },
  { display: "Santana de Pirapama", valueString: "pirapamense" },
  { display: "Santana do Deserto", valueString: "santanense" },
  { display: "Santana do Garambéu", valueString: "santanense" },
  { display: "Santana do Jacaré", valueString: "santanense" },
  { display: "Santana do Manhuaçu", valueString: "santanense" },
  { display: "Santana do Paraíso", valueString: "paraisense" },
  { display: "Santana do Riacho", valueString: "riachense" },
  { display: "Santana dos Montes", valueString: "santanense" },
  { display: "Santo Antônio do Amparo", valueString: "amparense" },
  { display: "Santo Antônio do Aventureiro", valueString: "aventureirense" },
  { display: "Santo Antônio do Grama", valueString: "gramense" },
  { display: "Santo Antônio do Itambé", valueString: "itambeano" },
  { display: "Santo Antônio do Jacinto", valueString: "santo-antoniense" },
  { display: "Santo Antônio do Monte", valueString: "santo-antoniense" },
  { display: "Santo Antônio do Retiro", valueString: "retirense" },
  { display: "Santo Antônio do Rio Abaixo", valueString: "santo-antoniense" },
  { display: "Santo Hipólito", valueString: "santo-hipolitense" },
  { display: "Santos Dumont", valueString: "sandumonense" },
  { display: "São Bento Abade", valueString: "são-bentense" },
  { display: "São Brás do Suaçuí", valueString: "suaçuiense" },
  { display: "São Domingos das Dores", valueString: "são-dominguense" },
  { display: "São Domingos do Prata", valueString: "pratense" },
  { display: "São Félix de Minas", valueString: "são-felense" },
  { display: "São Francisco", valueString: "são-franciscano" },
  { display: "São Francisco de Paula", valueString: "francisco-paulense" },
  { display: "São Francisco de Sales", valueString: "são-francisco-salense" },
  { display: "São Francisco do Glória", valueString: "franciscano" },
  { display: "São Geraldo", valueString: "são-geraldense" },
  { display: "São Geraldo da Piedade", valueString: "são-geraldense" },
  { display: "São Geraldo do Baixio", valueString: "baixiense" },
  { display: "São Gonçalo do Abaeté", valueString: "são-gonçalense" },
  { display: "São Gonçalo do Pará", valueString: "sãogonçalense" },
  { display: "São Gonçalo do Rio Abaixo", valueString: "sãogonçalense" },
  { display: "São Gonçalo do Rio Preto", valueString: "riopretano" },
  { display: "São Gonçalo do Sapucaí", valueString: "são-gonçalense" },
  { display: "São Gotardo", valueString: "são-gotardense" },
  { display: "São João Batista do Glória", valueString: "gloriense" },
  { display: "São João da Lagoa", valueString: "lagoano" },
  { display: "São João da Mata", valueString: "são-joanense" },
  { display: "São João da Ponte", valueString: "pontense" },
  { display: "São João das Missões", valueString: "missionense" },
  { display: "São João del-Rei", valueString: "são-joanense" },
  { display: "São João do Manhuaçu", valueString: "são-joanense" },
  {
    display: "São João do Manteninha",
    valueString: "manteniense , são-joanense",
  },
  { display: "São João do Oriente", valueString: "orientense" },
  { display: "São João do Pacuí", valueString: "pacuiense" },
  { display: "São João do Paraíso", valueString: "paraisense" },
  { display: "São João Evangelista", valueString: "peçanhense" },
  { display: "São João Nepomuceno", valueString: "são-joanense" },
  { display: "São Joaquim de Bicas", valueString: "são-joaquim-biquense" },
  { display: "São José da Barra", valueString: "barrense" },
  { display: "São José da Lapa", valueString: "lapense" },
  { display: "São José da Safira", valueString: "safirense" },
  { display: "São José da Varginha", valueString: "varginense-de-são-josé" },
  { display: "São José do Alegre", valueString: "alegrense" },
  { display: "São José do Divino", valueString: "divinense" },
  { display: "São José do Goiabal", valueString: "goiabalense" },
  { display: "São José do Jacuri", valueString: "jacuriense" },
  { display: "São José do Mantimento", valueString: "mantimentense" },
  { display: "São Lourenço", valueString: "são-lourenciano" },
  { display: "São Miguel do Anta", valueString: "sãomiguelense" },
  { display: "São Pedro da União", valueString: "sampetrense" },
  { display: "São Pedro do Suaçuí", valueString: "são pedrense" },
  { display: "São Pedro dos Ferros", valueString: "ferrense" },
  { display: "São Romão", valueString: "são-romanense" },
  { display: "São Roque de Minas", valueString: "sanroquense" },
  { display: "São Sebastião da Bela Vista", valueString: "bela-vistense" },
  {
    display: "São Sebastião da Vargem Alegre",
    valueString: "vargem-alegrense",
  },
  { display: "São Sebastião do Anta", valueString: "antense" },
  { display: "São Sebastião do Maranhão", valueString: "maranhense" },
  { display: "São Sebastião do Oeste", valueString: "oestiano" },
  { display: "São Sebastião do Paraíso", valueString: "paraisense" },
  { display: "São Sebastião do Rio Preto", valueString: "são-sebastianense" },
  { display: "São Sebastião do Rio Verde", valueString: "rioverdense" },
  { display: "São Tomé das Letras", valueString: "são-tomeense" },
  { display: "São Tiago", valueString: "são-tiaguense" },
  { display: "São Tomás de Aquino", valueString: "aquinense" },
  { display: "São Vicente de Minas", valueString: "vicenciano" },
  { display: "Sapucaí Mirim", valueString: "sapucaiense" },
  { display: "Sardoá", valueString: "sardoense" },
  { display: "Sarzedo", valueString: "sarzedense" },
  { display: "Sem-Peixe", valueString: "sem-peixeano" },
  { display: "Senador Amaral", valueString: "amaralense" },
  { display: "Senador Cortes", valueString: "senadorcortense" },
  { display: "Senador Firmino", valueString: "firminense, senadorense" },
  { display: "Senador José Bento", valueString: "senabentense" },
  { display: "Senador Modestino Gonçalves", valueString: "modestinense" },
  { display: "Senhora de Oliveira", valueString: "oliveirense" },
  { display: "Senhora do Porto", valueString: "portuense" },
  { display: "Senhora dos Remédios", valueString: "remediense" },
  { display: "Sericita", valueString: "sericitense" },
  { display: "Seritinga", valueString: "seritinguense" },
  { display: "Serra Azul de Minas", valueString: "serrazulense" },
  { display: "Serra da Saudade", valueString: "serrano-saudalense" },
  { display: "Serra do Salitre", valueString: "serralitrense" },
  { display: "Serra dos Aimorés", valueString: "serrense" },
  { display: "Serrania", valueString: "serraniense" },
  { display: "Serranópolis de Minas", valueString: "serranopolitano de minas" },
  { display: "Serranos", valueString: "serranense" },
  { display: "Serro", valueString: "serrano" },
  { display: "Sete Lagoas", valueString: "sete-lagoano" },
  { display: "Setubinha", valueString: "setubinhense" },
  { display: "Silverânia", valueString: "silveiraniense" },
  { display: "Silvianópolis", valueString: "silvianopolense" },
  { display: "Simão Pereira", valueString: "simonense" },
  { display: "Simonésia", valueString: "simonesiense" },
  { display: "Sobrália", valueString: "Sobraliense" },
  { display: "Soledade de Minas", valueString: "soledadense" },
  { display: "Tabuleiro", valueString: "tabuleirense" },
  { display: "Taiobeiras", valueString: "taiobeirense" },
  { display: "Taparuba", valueString: "taparubense" },
  { display: "Tapira", valueString: "tapirense" },
  { display: "Tapiraí", valueString: "tapiraiense" },
  { display: "Taquaraçu de Minas", valueString: "taquaraçuense" },
  { display: "Tarumirim", valueString: "tarumirinense" },
  { display: "Teixeiras", valueString: "teixeirense" },
  { display: "Teófilo Otoni", valueString: "teófilo-otonense" },
  { display: "Timóteo", valueString: "timotense" },
  { display: "Tiradentes", valueString: "tiradentino" },
  { display: "Tiros", valueString: "tirense" },
  { display: "Tocantins", valueString: "tocantinense" },
  { display: "Tocos do Moji", valueString: "tocosmojiense" },
  { display: "Toledo", valueString: "toledense" },
  { display: "Tombos", valueString: "tombense" },
  { display: "Três Corações", valueString: "tricordiano" },
  { display: "Três Marias", valueString: "trimariense" },
  { display: "Três Pontas", valueString: "três-pontano" },
  { display: "Tumiritinga", valueString: "tumiritinguense" },
  { display: "Tupaciguara", valueString: "tupaciguarense" },
  { display: "Turmalina", valueString: "turmalinense" },
  { display: "Turvolândia", valueString: "turvolandense" },
  { display: "Ubá", valueString: "ubaense" },
  { display: "Ubaí", valueString: "unaiense" },
  { display: "Ubaporanga", valueString: "ubaporanguense" },
  { display: "Uberaba", valueString: "uberabense" },
  { display: "Uberlândia", valueString: "uberlandense" },
  { display: "Umburatiba", valueString: "umburatibense" },
  { display: "Unaí", valueString: "unaiense" },
  { display: "União de Minas", valueString: "uniense" },
  { display: "Uruana de Minas", valueString: "uruanense" },
  { display: "Urucânia", valueString: "urucaniense" },
  { display: "Urucuia", valueString: "urucuiano" },
  { display: "Vargem Alegre", valueString: "vargem-alegrense" },
  { display: "Vargem Bonita", valueString: "vargeano" },
  { display: "Vargem Grande do Rio Pardo", valueString: "vargengrandense" },
  { display: "Varginha", valueString: "varginhense" },
  { display: "Varjão de Minas", valueString: "varjonense" },
  { display: "Várzea da Palma", valueString: "várzea-palmense ou varziano" },
  { display: "Varzelândia", valueString: "varzelandense" },
  { display: "Vazante", valueString: "vazantino" },
  { display: "Verdelândia", valueString: "verdelandense" },
  { display: "Veredinha", valueString: "veredinhense" },
  { display: "Veríssimo", valueString: "verissimense" },
  { display: "Vermelho Novo", valueString: "vermelhense" },
  { display: "Vespasiano", valueString: "vespasianense" },
  { display: "Viçosa", valueString: "viçosense" },
  { display: "Vieiras", valueString: "vieirense" },
  { display: "Virgem da Lapa", valueString: "virgolapense" },
  { display: "Virgínia", valueString: "virginense" },
  { display: "Virginópolis", valueString: "virginopolitano" },
  { display: "Virgolândia", valueString: "virgolandense" },
  { display: "Visconde do Rio Branco", valueString: "rio-branquense" },
  { display: "Volta Grande", valueString: "voltagrandense" },
];

const fs = require("fs");

const conteudo = fs.readFileSync("../base/municipios.json", "utf-8");
const municipios = JSON.parse(conteudo);

function gentilicoDe(m) {
  let encontrado = entrada.find((e) => e.display === m);
  if (encontrado) {
    return encontrado.valueString;
  }

  return "";
}

function removeDigitoVerificador(codigo) {
  return Math.floor(codigo / 10);
}

function toConcept(m) {
  return {
    code: removeDigitoVerificador(m.ibge),
    display: m.nome,
    property: [
      {
        code: "type",
        valueCode: "city",
      },
      {
        code: "ethnical",
        valueString: gentilicoDe(m.nome),
      },
    ],
  };
}

function obtemEstado(ibge) {
  return ibge.toString().substring(0, 2);
}

let conceitos = municipios.map((m) => toConcept(m));
let porEstado = new Map();

conceitos.forEach((c) => {
  let estado = obtemEstado(c.code);
  let cidades = porEstado.get(estado);
  if (!cidades) {
    cidades = [];
    porEstado.set(estado, cidades);
  }

  cidades.push(c);
});

let saida = JSON.stringify(porEstado.get("31"));
console.log(saida);
