const entrada = [
  { display: "Adamantina", valueString: "adamantinense" },
  { display: "Adolfo", valueString: "adolfino" },
  { display: "Aguaí", valueString: "aguaiano" },
  { display: "Águas de Lindóia", valueString: "lindoiense" },
  { display: "Águas da Prata", valueString: "água-pratense" },
  { display: "Águas de Santa Bárbara", valueString: "santa-barbarense" },
  { display: "Águas de São Pedro", valueString: "água-pedrense" },
  { display: "Agudos", valueString: "agudense" },
  { display: "Alambari", valueString: "alambariense" },
  { display: "Alfredo Marcondes", valueString: "marcondense" },
  { display: "Altair", valueString: "altairense" },
  { display: "Altinópolis", valueString: "altinopolense" },
  { display: "Alto Alegre", valueString: "alto-alegrense" },
  { display: "Alumínio", valueString: "aluminense" },
  { display: "Álvares Florence", valueString: "florencense" },
  { display: "Álvares Machado", valueString: "machadense" },
  { display: "Álvaro de Carvalho", valueString: "álvaro-carvalhense" },
  { display: "Alvinlândia", valueString: "alvinlandense" },
  { display: "Americana", valueString: "americanense" },
  { display: "Américo Brasiliense", valueString: "ameriliense" },
  {
    display: "Américo de Campos",
    valueString: "américo-campista ou americampense",
  },
  { display: "Amparo", valueString: "amparense" },
  { display: "Analândia", valueString: "analandense" },
  { display: "Andradina", valueString: "andradinense" },
  { display: "Angatuba", valueString: "angatubense" },
  { display: "Anhembi", valueString: "anhembiense" },
  { display: "Anhumas", valueString: "anhumense" },
  { display: "Aparecida", valueString: "aparecidense" },
  { display: "Aparecida d'Oeste", valueString: "oesteaparecidense" },
  { display: "Apiaí", valueString: "apiaiense" },
  { display: "Araçariguama", valueString: "araçariguamense" },
  { display: "Araçatuba", valueString: "araçatubense" },
  { display: "Araçoiaba da Serra", valueString: "araçoiabano" },
  { display: "Aramina", valueString: "araminense" },
  { display: "Arandu", valueString: "aranduense" },
  { display: "Arapeí", valueString: "arapeiense" },
  { display: "Araraquara", valueString: "araraquarense" },
  { display: "Araras", valueString: "ararense" },
  { display: "Arco-Íris", valueString: "arco-irense" },
  { display: "Arealva", valueString: "arealvense" },
  { display: "Areias", valueString: "areiense" },
  { display: "Areiópolis", valueString: "Areiopolitano" },
  { display: "Ariranha", valueString: "ariranhense" },
  { display: "Artur Nogueira", valueString: "nogueirense" },
  { display: "Arujá", valueString: "arujaense" },
  { display: "Aspásia", valueString: "aspasiense" },
  { display: "Assis", valueString: "assisense" },
  { display: "Atibaia", valueString: "atibaiense ou atibaiano" },
  { display: "Auriflama", valueString: "auriflamense" },
  { display: "Avaí", valueString: "avaiense" },
  { display: "Avanhandava", valueString: "avanhandavense" },
  { display: "Avaré", valueString: "avareense" },
  { display: "Bady Bassitt", valueString: "badiense, bassitense" },
  { display: "Balbinos", valueString: "balbinense" },
  { display: "Bálsamo", valueString: "balsamense" },
  { display: "Bananal", valueString: "bananalense" },
  { display: "Barão de Antonina", valueString: "barão-antoniniense" },
  { display: "Barbosa", valueString: "barbosense" },
  { display: "Bariri", valueString: "baririense" },
  { display: "Barra Bonita", valueString: "barra-bonitense" },
  { display: "Barra do Chapéu", valueString: "barrense" },
  { display: "Barra do Turvo", valueString: "barra-turvense" },
  { display: "Barretos", valueString: "barretense" },
  { display: "Barrinha", valueString: "barrinhense" },
  { display: "Barueri", valueString: "barueriense" },
  { display: "Bastos", valueString: "bastense" },
  { display: "Batatais", valueString: "batataense" },
  { display: "Bauru", valueString: "bauruense" },
  { display: "Bebedouro", valueString: "bebedourense" },
  { display: "Bento de Abreu", valueString: "bento-abreuense" },
  { display: "Bernardino de Campos", valueString: "bernardinense" },
  { display: "Bertioga", valueString: "bertioguense" },
  { display: "Bilac", valueString: "bilaquense" },
  { display: "Birigui", valueString: "biriguiense" },
  { display: "Biritiba Mirim", valueString: "biritibense" },
  { display: "Boa Esperança do Sul", valueString: "boa-esperancense" },
  { display: "Bocaina", valueString: "bocainense" },
  { display: "Bofete", valueString: "bofetense" },
  { display: "Boituva", valueString: "boituvense" },
  { display: "Bom Jesus dos Perdões -" },
  { display: "Bom Sucesso de Itararé -" },
  { display: "Borá", valueString: "boraense" },
  { display: "Boraceia", valueString: "boraceense" },
  { display: "Borborema", valueString: "borboremense" },
  { display: "Borebi", valueString: "borebiense" },
  { display: "Botucatu", valueString: "botucatuense" },
  { display: "Bragança Paulista", valueString: "bragantino" },
  { display: "Braúna", valueString: "braunense" },
  { display: "Brejo Alegre", valueString: "brejo-alegrense" },
  { display: "Brodowski", valueString: "brodosquiano" },
  { display: "Brotas", valueString: "brotense" },
  { display: "Buri", valueString: "buriense" },
  { display: "Buritama", valueString: "buritamense" },
  { display: "Buritizal", valueString: "buritizalense" },
  { display: "Cabrália Paulista", valueString: "cabraliense" },
  { display: "Cabreúva", valueString: "cabreuvano" },
  { display: "Caçapava", valueString: "caçapavense" },
  { display: "Cachoeira Paulista", valueString: "cachoeirense" },
  { display: "Caconde", valueString: "cacondense" },
  { display: "Cafelândia", valueString: "cafelandense" },
  { display: "Caiabu", valueString: "caiabuense" },
  { display: "Caieiras", valueString: "caieirense" },
  { display: "Caiuá", valueString: "caiuaense" },
  { display: "Cajamar", valueString: "cajamarense" },
  { display: "Cajati", valueString: "cajatiense" },
  { display: "Cajobi", valueString: "cajobiense" },
  { display: "Cajuru", valueString: "cajuruense" },
  {
    display: "Campina do Monte Alegre",
    valueString: "monte-alegrense, campino",
  },
  { display: "Campinas", valueString: "campineiro" },
  { display: "Campo Limpo Paulista", valueString: "campo-limpense" },
  { display: "Campos do Jordão", valueString: "jordanense" },
  { display: "Campos Novos Paulista", valueString: "campo-limpense" },
  { display: "Cananeia", valueString: "cananeiense" },
  { display: "Canas", valueString: "canense" },
  { display: "Cândido Mota", valueString: "cândido-motense" },
  { display: "Cândido Rodrigues", valueString: "candido-rodriguense" },
  { display: "Canitar", valueString: "canitarense" },
  { display: "Capão Bonito", valueString: "capão-bonitense" },
  { display: "Capela do Alto", valueString: "capelense" },
  { display: "Capivari", valueString: "capivariano" },
  { display: "Caraguatatuba", valueString: "caraguatatubense" },
  { display: "Carapicuíba", valueString: "carapicuibano" },
  { display: "Cardoso", valueString: "cardosense" },
  { display: "Casa Branca", valueString: "casa-branquense" },
  { display: "Cássia dos Coqueiros", valueString: "cássia-dos-coqueirenses" },
  { display: "Castilho", valueString: "castilhense" },
  { display: "Catanduva", valueString: "catanduvense" },
  { display: "Catiguá", valueString: "catiguaense" },
  { display: "Cedral", valueString: "cedralense" },
  { display: "Cerqueira César", valueString: "cerqueirense" },
  { display: "Cerquilho", valueString: "cerquilhense" },
  { display: "Cesário Lange", valueString: "cesário-langense" },
  { display: "Charqueada", valueString: "charqueadense" },
  { display: "Chavantes", valueString: "chavantense" },
  { display: "Clementina", valueString: "clementinense" },
  { display: "Colina", valueString: "colinense" },
  { display: "Colômbia", valueString: "colombiense" },
  { display: "Conchal", valueString: "conchalense" },
  { display: "Conchas", valueString: "conchense" },
  { display: "Cordeirópolis", valueString: "cordeiropolense" },
  { display: "Coroados", valueString: "coroadense" },
  { display: "Coronel Macedo", valueString: "macedense" },
  { display: "Corumbataí", valueString: "corumbataiense" },
  { display: "Cosmópolis", valueString: "cosmopolense" },
  { display: "Cosmorama", valueString: "cosmoramense" },
  { display: "Cotia", valueString: "cotiano" },
  { display: "Cravinhos", valueString: "cravinhense" },
  { display: "Cristais Paulista", valueString: "cristalense" },
  { display: "Cruzália", valueString: "cruzaliense" },
  { display: "Cruzeiro", valueString: "cruzeirense" },
  { display: "Cubatão", valueString: "cubatonense" },
  { display: "Cunha", valueString: "cunhense" },
  { display: "Descalvado", valueString: "descalvadense" },
  { display: "Diadema", valueString: "diademense" },
  { display: "Dirce Reis", valueString: "dircense" },
  { display: "Divinolândia", valueString: "divinolandense" },
  { display: "Dobrada", valueString: "dobradense" },
  { display: "Dois Córregos", valueString: "dois-correguense" },
  { display: "Dolcinópolis", valueString: "dolcinopolense" },
  { display: "Dourado", valueString: "douradense" },
  { display: "Dracena", valueString: "dracenense" },
  { display: "Duartina", valueString: "duartinense" },
  { display: "Dumont", valueString: "dumonense" },
  { display: "Echaporã", valueString: "echaporense" },
  { display: "Eldorado", valueString: "eldoradense" },
  { display: "Elias Fausto", valueString: "elias-faustense" },
  { display: "Elisiário", valueString: "elisiariense" },
  { display: "Embaúba", valueString: "embaubense" },
  { display: "Embu das Artes", valueString: "embuense" },
  { display: "Embu-Guaçu", valueString: "embu-guaçuense" },
  {
    display: "Engenheiro Coelho",
    valueString: "coelhense, engenheiro-coelhense",
  },
  { display: "Espírito Santo do Pinhal", valueString: "pinhalense" },
  { display: "Espírito Santo do Turvo", valueString: "espírito-santense" },
  { display: "Estiva Gerbi", valueString: "estivense" },
  { display: "Estrela d'Oeste", valueString: "estrelense" },
  { display: "Estrela do Norte", valueString: "estrelense" },
  { display: "Euclides da Cunha Paulista", valueString: "euclidense" },
  { display: "Fartura", valueString: "farturense" },
  { display: "Fernando Prestes", valueString: "fernando-prestense" },
  { display: "Fernandópolis", valueString: "fernandopolense" },
  { display: "Ferraz de Vasconcelos", valueString: "ferrazense" },
  { display: "Franca", valueString: "francano" },
  { display: "Francisco Morato", valueString: "moratense" },
  { display: "Franco da Rocha", valueString: "franco-rochense" },
  { display: "Guariba", valueString: "guaribense" },
  { display: "Guarujá", valueString: "guarujaense" },
  { display: "Gavião Peixoto", valueString: "gavionense" },
  { display: "Guaíra", valueString: "guairense" },
  { display: "Guapiara", valueString: "guapiarense" },
  { display: "Guaratinguetá", valueString: "guaratinguetaense" },
  { display: "Guareí", valueString: "guareiense" },
  { display: "Guarulhos", valueString: "guarulhense" },
  { display: "Guarujá", valueString: "guarujaense" },
  { display: "Guatapará", valueString: "guarataparaense" },
  { display: "Herculândia", valueString: "herculandense" },
  { display: "Holambra", valueString: "holambrense" },
  { display: "Hortolândia", valueString: "hortolandense" },
  { display: "Iacanga", valueString: "iacanguense" },
  { display: "Iacri", valueString: "iacriense" },
  { display: "Iaras", valueString: "iarense" },
  { display: "Ibaté", valueString: "ibateense" },
  { display: "Ibirá", valueString: "ibiraense" },
  { display: "Ibirarema", valueString: "ibiraremense" },
  { display: "Ibitinga", valueString: "ibitinguense" },
  { display: "Ibiúna", valueString: "ibiunense" },
  { display: "Icém", valueString: "icemense" },
  { display: "Iepê", valueString: "iepense" },
  { display: "Igaraçu do Tietê", valueString: "igaraçuense" },
  { display: "Igarapava", valueString: "igarapavense" },
  { display: "Igaratá", valueString: "igaratense" },
  { display: "Iguape", valueString: "iguapense" },
  { display: "Ilha Comprida", valueString: "Ilha Compridense" },
  { display: "Ilha Solteira", valueString: "ilheense" },
  { display: "Ilhabela", valueString: "ilhabelense" },
  { display: "Indaiatuba", valueString: "indaiatubano" },
  { display: "Indiana", valueString: "indianense" },
  { display: "Indiaporã", valueString: "indiaporãense" },
  { display: "Inúbia Paulista", valueString: "inubiênse" },
  { display: "Ipaussu", valueString: "ipaussuense" },
  { display: "Iperó", valueString: "iperoense" },
  { display: "Ipeúna", valueString: "ipeunense" },
  { display: "Ipiguá", valueString: "ipiguaense" },
  { display: "Iporanga", valueString: "iporanguense" },
  { display: "Ipuã", valueString: "ipuanense" },
  { display: "Iracemápolis", valueString: "iracemapolense" },
  { display: "Irapuã", valueString: "irapuanense" },
  { display: "Irapuru -irapuruense" },
  { display: "Itaberá", valueString: "itaberaense" },
  { display: "Itaí", valueString: "itaiense" },
  { display: "Itajobi", valueString: "itajobiense" },
  { display: "Itaju", valueString: "itajuense" },
  { display: "Itanhaém", valueString: "itanhaense" },
  { display: "Itaoca", valueString: "itaoquense" },
  { display: "Itapecerica da Serra", valueString: "itapecericano" },
  { display: "Itapetininga", valueString: "itapetiningano" },
  { display: "Itapeva", valueString: "itapevense" },
  { display: "Itapevi", valueString: "itapeviense" },
  { display: "Itapira", valueString: "itapirense" },
  { display: "Itapirapuã Paulista", valueString: "itapirapuense-paulista" },
  { display: "Itápolis", valueString: "itapolitano" },
  { display: "Itaporanga", valueString: "itaporanguense" },
  { display: "Itapuí", valueString: "itapuiense" },
  { display: "Itapura", valueString: "itapurense" },
  { display: "Itaquaquecetuba", valueString: "itaquaquecetubano" },
  { display: "Itararé", valueString: "itarareense" },
  { display: "Itariri", valueString: "itaririense" },
  { display: "Itatiba", valueString: "itatibense" },
  { display: "Itatinga", valueString: "itatinguense" },
  { display: "Itirapina", valueString: "itirapinense" },
  { display: "Itirapuã", valueString: "Itirapuã" },
  { display: "Itobi", valueString: "itobiense" },
  { display: "Itu", valueString: "ituano" },
  { display: "Itupeva", valueString: "itupevense" },
  { display: "Ituverava", valueString: "ituveravense" },
  { display: "Jaborandi", valueString: "jaborandiense" },
  { display: "Jaboticabal", valueString: "jaboticabalense" },
  { display: "Jacareí", valueString: "jacareiense" },
  { display: "Jaci", valueString: "jaciense" },
  { display: "Jacupiranga", valueString: "jacupiranguense" },
  { display: "Jaguariúna", valueString: "jaguariunense" },
  { display: "Jales", valueString: "jalesense" },
  { display: "Jambeiro -jambeirense" },
  { display: "Jandira", valueString: "jandirense" },
  { display: "Jardinópolis", valueString: "jardinopolense" },
  { display: "Jarinu", valueString: "jarinuense" },
  { display: "Jaú", valueString: "jauense" },
  { display: "Jeriquara", valueString: "jeriquarense" },
  { display: "Joanópolis", valueString: "joanopolense" },
  { display: "João Ramalho", valueString: "ramalhense" },
  { display: "José Bonifácio", valueString: "bonifaciano" },
  { display: "Júlio Mesquita", valueString: "júlio-mesquitense" },
  { display: "Jumirim", valueString: "jumirense" },
  { display: "Jundiaí", valueString: "jundiaiense" },
  { display: "Junqueirópolis", valueString: "junqueiropolense" },
  { display: "Juquiá", valueString: "juquiaense" },
  { display: "Juquitiba", valueString: "juquitibense" },
  { display: "Lagoinha", valueString: "lagoinhense" },
  { display: "Laranjal Paulista", valueString: "laranjalense" },
  { display: "Lavínia", valueString: "lavinense" },
  { display: "Lavrinhas", valueString: "lavrinhense" },
  { display: "Leme", valueString: "lemense" },
  { display: "Lençóis Paulista", valueString: "lençoense" },
  { display: "Limeira", valueString: "limeirense" },
  { display: "Lindóia", valueString: "lindoiano" },
  { display: "Lins", valueString: "linense" },
  { display: "Lorena", valueString: "lorenense" },
  { display: "Lourdes", valueString: "lourdense" },
  { display: "Louveira", valueString: "louveirense" },
  { display: "Lucélia", valueString: "luceliense" },
  { display: "Lucianópolis", valueString: "lucianopolense" },
  { display: "Luís Antônio", valueString: "luís-antoniense" },
  { display: "Luiziânia", valueString: "luisianense" },
  { display: "Lupércio", valueString: "lupercense" },
  { display: "Lutécia", valueString: "luteciano" },
  { display: "Macatuba", valueString: "macatubense" },
  { display: "Macedônia", valueString: "macedonienses" },
  { display: "Magda", valueString: "magdense" },
  { display: "Mairinque", valueString: "mairinquense" },
  { display: "Mairiporã", valueString: "mairiporense, mairiporanense" },
  { display: "Manduri", valueString: "manduriense" },
  {
    display: "Marabá Paulista",
    valueString: "marabaense ou marabá-paulistense",
  },
  { display: "Maracaí", valueString: "maracaiense" },
  { display: "Marapoama", valueString: "marapoamense" },
  { display: "Mariápolis", valueString: "mariapolense" },
  { display: "Marília", valueString: "mariliense" },
  { display: "Marinópolis", valueString: "marinopolense" },
  { display: "Martinópolis", valueString: "martinopolense" },
  { display: "Matão", valueString: "matonense" },
  { display: "Mauá", valueString: "mauaense" },
  { display: "Mendonça", valueString: "mendocino" },
  { display: "Meridiano", valueString: "meridianense" },
  { display: "Mesópolis", valueString: "mesopolense" },
  { display: "Miguelópolis", valueString: "miguelopense" },
  { display: "Mineiros do Tietê", valueString: "mineiros-tieteense" },
  { display: "Mira Estrela", valueString: "mira-estrelense" },
  { display: "Miracatu", valueString: "miracatuense" },
  { display: "Mirandópolis", valueString: "mirandopolense" },
  { display: "Mirante do Paranapanema", valueString: "mirantense" },
  { display: "Mirassol", valueString: "mirassolense" },
  { display: "Mirassolândia", valueString: "mirassolandense" },
  { display: "Mococa", valueString: "mocoquense" },
  { display: "Mogi das Cruzes", valueString: "mojiano ou mogiano" },
  { display: "Mogi Guaçu", valueString: "guaçuano" },
  { display: "Mogi Mirim", valueString: "moji-miriano ou mogimiriano" },
  { display: "Mombuca", valueString: "mombucano" },
  { display: "Monções", valueString: "monçolense" },
  { display: "Mongaguá", valueString: "mongaguaense" },
  { display: "Monte Alegre do Sul", valueString: "monte-alegrense" },
  { display: "Monte Alto", valueString: "monte-altense" },
  { display: "Monte Aprazível", valueString: "monte-aprazivelense" },
  { display: "Monte Azul Paulista", valueString: "monte-azulense" },
  { display: "Monte Castelo", valueString: "montecastelense" },
  { display: "Monte Mor", valueString: "monte-morense" },
  { display: "Monteiro Lobato", valueString: "lobatense" },
  { display: "Morro Agudo", valueString: "morroagudense" },
  { display: "Morungaba", valueString: "morungabense" },
  { display: "Motuca", valueString: "motuquense" },
  { display: "Murutinga do Sul", valueString: "murutinguense" },
  { display: "Nantes", valueString: "nantense" },
  { display: "Narandiba", valueString: "narandibense" },
  { display: "Natividade da Serra", valueString: "nativense" },
  { display: "Nazaré Paulista", valueString: "nazareano" },
  { display: "Neves Paulista", valueString: "nevense" },
  { display: "Nhandeara", valueString: "nhandearense" },
  { display: "Nipoã", valueString: "nipoense" },
  { display: "Nova Aliança", valueString: "aliancense" },
  { display: "Nova Campina", valueString: "nova-campinense" },
  { display: "Nova Canaã Paulista", valueString: "nova-canaense" },
  { display: "Nova Castilho", valueString: "nova-castilhense" },
  { display: "Nova Europa", valueString: "nova-europense" },
  { display: "Nova Granada", valueString: "granadense" },
  { display: "Nova Guataporanga", valueString: "guataporanguense" },
  { display: "Nova Independência", valueString: "independentino" },
  { display: "Nova Luzitânia", valueString: "luzitaniense" },
  { display: "Nova Odessa", valueString: "nova-odessense" },
  { display: "Novais", valueString: "novaense" },
  { display: "Novo Horizonte", valueString: "novo-horizontino" },
  { display: "Nuporanga", valueString: "nuporanguense" },
  { display: "Ocauçu", valueString: "ocauçuense" },
  { display: "Óleo", valueString: "oleense" },
  { display: "Olímpia", valueString: "olimpiense" },
  { display: "Onda Verde", valueString: "onda-verdense" },
  { display: "Oriente", valueString: "orientense ou orientalense" },
  { display: "Orindiúva", valueString: "orindiuvense" },
  { display: "Orlândia", valueString: "orlandino" },
  { display: "Osasco", valueString: "osasquense, osasquiano" },
  { display: "Oscar Bressane", valueString: "bressanense" },
  { display: "Osvaldo Cruz", valueString: "osvaldo-cruzense" },
  { display: "Ourinhos", valueString: "ourinhense" },
  { display: "Ouro Verde", valueString: "ouroverdense" },
  { display: "Ouroeste", valueString: "ouroestense" },
  { display: "Palestina", valueString: "palestinense" },
  { display: "Palmeira d'Oeste", valueString: "palmeirense" },
  { display: "Pariquera-Açu", valueString: "pariquerense" },
  { display: "Paulínia", valueString: "paulinense" },
  { display: "Pederneiras", valueString: "pederneirense" },
  { display: "Pedra Bela", valueString: "pedra-belense" },
  { display: "Pedreira", valueString: "pedreirense" },
  { display: "Penápolis", valueString: "penapolense" },
  { display: "Pedrinhas Paulista", valueString: "pedrinhense" },
  { display: "Peruíbe", valueString: "peruibense" },
  { display: "Pilar do Sul", valueString: "pilarense" },
  { display: "Pindamonhangaba", valueString: "pindamonhangabense" },
  { display: "Pindorama", valueString: "pindoramense" },
  { display: "Piracaia", valueString: "piracaiense" },
  { display: "Piracicaba", valueString: "piracicabano" },
  { display: "Piraju", valueString: "pirajuense" },
  { display: "Pirajuí", valueString: "pirajuiense" },
  {
    display: "Pirapora do Bom Jesus",
    valueString: "piraporano, piraporense, piraporoense, bom-jesusiano",
  },
  { display: "Pirassununga", valueString: "piraçununguense" },
  { display: "Poá", valueString: "poaense" },
  { display: "Pompeia", valueString: "pompeense" },
  { display: "Pontal", valueString: "pontalense" },
  { display: "Porto Feliz", valueString: "porto-felicense" },
  { display: "Porto Ferreira", valueString: "ferreirense" },
  { display: "Praia Grande", valueString: "praia-grandense" },
  { display: "Presidente Alves", valueString: "alvense" },
  { display: "Presidente Bernardes", valueString: "bernardense" },
  { display: "Presidente Epitácio", valueString: "epitaciano" },
  { display: "Presidente Prudente", valueString: "prudentino" },
  { display: "Presidente Venceslau", valueString: "venceslauense" },
  { display: "Promissão", valueString: "promissense" },
  { display: "Quadra", valueString: "quadrense" },
  { display: "Quatá", valueString: "quataense" },
  { display: "Queiroz", valueString: "queirosense" },
  { display: "Queluz", valueString: "queluzense" },
  { display: "Quintana", valueString: "quintanense" },
  { display: "Registro", valueString: "registrense" },
  { display: "Ribeirão Bonito", valueString: "ribeirão-bonitense" },
  { display: "Ribeirão Branco", valueString: "ribeirão-branquense" },
  { display: "Ribeirão Pires", valueString: "ribeirão-pirense" },
  { display: "Ribeirão Preto", valueString: "ribeirão-pretano" },
  { display: "Rincão", valueString: "rinconense" },
  { display: "Rinópolis", valueString: "rinopolense" },
  { display: "Rio Claro", valueString: "rio-clarense" },
  { display: "Riversul", valueString: "riversulense" },
  { display: "Sabino", valueString: "sabinense" },
  { display: "Sagres", valueString: "sagrense" },
  { display: "Sales", valueString: "salense" },
  { display: "Sales Oliveira", valueString: "salense" },
  { display: "Salesópolis", valueString: "salesopolense" },
  { display: "Salmourão", valueString: "salmoroense" },
  { display: "Saltinho", valueString: "saltinhense" },
  { display: "Salto", valueString: "saltense" },
  { display: "Salto de Pirapora –saltopiraporense" },
  { display: "Salto Grande", valueString: "salto-grandense" },
  { display: "Sandovalina", valueString: "sandovalinense" },
  { display: "Santa Adélia", valueString: "santa-adeliense" },
  { display: "Santa Albertina", valueString: "santa-albertinense" },
  { display: "Santa Bárbara d'Oeste", valueString: "barbarense" },
  { display: "Santa Branca", valueString: "santa-branquense" },
  { display: "Santa Clara d'Oeste", valueString: "santa clarense" },
  { display: "Santa Cruz da Conceição", valueString: "santa-cruzense" },
  { display: "Santa Cruz da Esperança", valueString: "santacruzense" },
  { display: "Santa Cruz das Palmeiras", valueString: "palmeirense" },
  { display: "Santa Cruz do Rio Pardo", valueString: "santa-cruzense" },
  { display: "Santa Ernestina", valueString: "santa-ernestinense" },
  { display: "Santa Fé do Sul", valueString: "santa-fé-sulense" },
  { display: "Santa Gertrudes", valueString: "gertrudense" },
  { display: "Santa Isabel", valueString: "santa isabelense" },
  { display: "Santa Lúcia", valueString: "santa-luciense" },
  { display: "Santa Maria da Serra", valueString: "santamaria-serrense" },
  { display: "Santa Mercedes", valueString: "mercedense" },
  { display: "Santa Rita d'Oeste", valueString: "santa-ritense" },
  { display: "Santa Rita do Passa Quatro", valueString: "santa-ritense" },
  { display: "Santa Rosa de Viterbo", valueString: "santa-rosense" },
  { display: "Santa Salete", valueString: "saletense" },
  { display: "Santana da Ponte Pensa", valueString: "santanense" },
  { display: "Santana de Parnaíba", valueString: "parnaibano" },
  { display: "Santo Anastácio", valueString: "anastaciano" },
  { display: "Santo André", valueString: "andreense" },
  { display: "Santo Antônio da Alegria", valueString: "alegriense" },
  { display: "Santo Antônio de Posse", valueString: "possense" },
  { display: "Santo Antônio do Aracanguá", valueString: "aracanguaense" },
  { display: "Santo Antônio do Jardim", valueString: "jardinense" },
  { display: "Santo Antônio do Pinhal", valueString: "pinhalense" },
  { display: "Santo Expedito", valueString: "expeditense" },
  { display: "Santópolis do Aguapeí", valueString: "santopolense" },
  { display: "Santos", valueString: "santista" },
  { display: "São Bento do Sapucaí", valueString: "são-bentista" },
  { display: "São Bernardo do Campo", valueString: "são-bernardense" },
  { display: "São Caetano do Sul", valueString: "sul-caetanense" },
  {
    display: "São Carlos",
    valueString: "são-carlense (sancarlense) ou carlopolitano",
  },
  { display: "São Francisco", valueString: "são-francisquense" },
  {
    display: "São João da Boa Vista",
    valueString: "são-joanense (sanjoanense)",
  },
  { display: "São João das Duas Pontes", valueString: "são-joanense" },
  { display: "São João de Iracema", valueString: "iracemense" },
  { display: "São João do Pau-d'Alho", valueString: "paudalhense" },
  { display: "São Joaquim da Barra", valueString: "joaquinense" },
  { display: "São José da Bela Vista", valueString: "belavistense" },
  { display: "São José do Barreiro", valueString: "barreirense" },
  { display: "São José do Rio Pardo", valueString: "rio-pardense" },
  { display: "São José do Rio Preto", valueString: "rio-pretense" },
  { display: "São José dos Campos", valueString: "joseense" },
  { display: "São Lourenço da Serra", valueString: "são-lourensano" },
  { display: "São Luiz do Paraitinga", valueString: "luisense" },
  { display: "São Manuel", valueString: "são-manuelense" },
  { display: "São Miguel Arcanjo", valueString: "são-miguelense" },
  { display: "São Paulo", valueString: "paulistano" },
  { display: "São Pedro", valueString: "são-pedrense" },
  { display: "São Pedro do Turvo", valueString: "são-pedrense" },
  { display: "São Roque", valueString: "são-roquense" },
  { display: "São Sebastião", valueString: "sebastianense" },
  { display: "São Sebastião da Grama", valueString: "gramense" },
  { display: "São Simão", valueString: "simonense" },
  { display: "São Vicente", valueString: "vicentino e calunga" },
  { display: "Sarapuí", valueString: "sarapuiano" },
  { display: "Sarutaiá", valueString: "sarutaiense" },
  { display: "Sebastianópolis do Sul", valueString: "sebastionopolense" },
  { display: "Serra Azul", valueString: "serra-azulense" },
  { display: "Serra Negra", valueString: "serrano" },
  { display: "Serrana", valueString: "serranense" },
  { display: "Sertãozinho", valueString: "sertanezino" },
  { display: "Sete Barras", valueString: "sete-barrense" },
  { display: "Socorro", valueString: "socorrense" },
  { display: "Sorocaba", valueString: "sorocabano" },
  { display: "Sumaré", valueString: "sumareense" },
  { display: "Suzano", valueString: "suzanense" },
  { display: "Tabapuã", valueString: "tabapuanense" },
  { display: "Tabatinga", valueString: "tabatinguense" },
  { display: "Taboão da Serra", valueString: "taboanense" },
  { display: "Taciba", valueString: "tacibense" },
  { display: "Taguaí", valueString: "taguaiense ou taguaíno" },
  { display: "Taiaçu", valueString: "taiaçuense" },
  { display: "Taiuva", valueString: "taiuvense" },
  { display: "Tambaú", valueString: "tambausense" },
  { display: "Tanabi", valueString: "tanabiense" },
  { display: "Tapiraí", valueString: "tapiraiense" },
  { display: "Tapiratiba", valueString: "tapiratibense" },
  { display: "Taquaral", valueString: "taquaralense" },
  { display: "Taquaritinga", valueString: "taquaritinguense" },
  { display: "Taquarituba", valueString: "taquaritubense" },
  { display: "Taquarivaí", valueString: "taquarivaense" },
  { display: "Tarabai", valueString: "tarabainos" },
  { display: "Tarumã", valueString: "tarumaense" },
  { display: "Tatuí", valueString: "tatuiano" },
  { display: "Taubaté", valueString: "taubateano ou taubateense" },
  { display: "Tejupá", valueString: "tejupaense" },
  { display: "Teodoro Sampaio", valueString: "teodorense" },
  { display: "Terra Roxa", valueString: "terra-roxense" },
  { display: "Tietê", valueString: "tieteense" },
  { display: "Timburi", valueString: "timburiense" },
  { display: "Torre de Pedra", valueString: "torrepedrense" },
  { display: "Torrinha", valueString: "torrinhense" },
  { display: "Trabiju", valueString: "trabijuense" },
  { display: "Tremembé", valueString: "tremembeense" },
  { display: "Três Fronteiras", valueString: "trifronteirano" },
  { display: "Tuiuti", valueString: "tuiutiense" },
  { display: "Tupã", valueString: "tupãense" },
  { display: "Tupi Paulista", valueString: "tupiense" },
  { display: "Turiúba", valueString: "turiubense" },
  { display: "Turmalina", valueString: "turmalinense" },
  { display: "Ubarana", valueString: "ubaranense" },
  { display: "Ubatuba", valueString: "ubatubense" },
  { display: "Ubirajara", valueString: "ubirajarense" },
  { display: "Uchoa", valueString: "uchoense" },
  { display: "União Paulista", valueString: "união-paulistense" },
  { display: "Urânia", valueString: "uraniano" },
  { display: "Uru", valueString: "uruense" },
  { display: "Urupês", valueString: "urupeense" },
  { display: "Valentim Gentil", valueString: "valentim-gentilense" },
  { display: "Valinhos", valueString: "valinhense" },
  { display: "Valparaíso", valueString: "valparaisense" },
  { display: "Vargem", valueString: "vargense" },
  { display: "Vargem Grande do Sul", valueString: "vargem-grandense" },
  { display: "Vargem Grande Paulista", valueString: "vargem-grandense" },
  { display: "Várzea Paulista", valueString: "varzino" },
  { display: "Vera Cruz", valueString: "vera-cruzense" },
  { display: "Vinhedo", valueString: "vinhedense" },
  { display: "Viradouro", valueString: "viradourense" },
  { display: "Vista Alegre do Alto", valueString: "vistalegrense" },
  { display: "Vitória Brasil", valueString: "vitoriabrasiliense" },
  { display: "Votorantim", valueString: "votorantinense" },
  { display: "Votuporanga", valueString: "votuporanguense" },
  { display: "Zacarias", valueString: "zacariense" },
];

const fs = require("fs");

const conteudo = fs.readFileSync("../base/municipios.json", "utf-8");
const municipios = JSON.parse(conteudo);

function gentilicoDe(m) {
  let encontrado = entrada.find((e) => e.display === m);
  if (encontrado) {
    return encontrado.valueString;
  }

  return "";
}

function removeDigitoVerificador(codigo) {
  return Math.floor(codigo / 10);
}

function toConcept(m) {
  return {
    code: removeDigitoVerificador(m.ibge),
    display: m.nome,
    property: [
      {
        code: "type",
        valueCode: "city",
      },
      {
        code: "ethnical",
        valueString: gentilicoDe(m.nome),
      },
    ],
  };
}

function obtemEstado(ibge) {
  return ibge.toString().substring(0, 2);
}

let conceitos = municipios.map((m) => toConcept(m));
let porEstado = new Map();

conceitos.forEach((c) => {
  let estado = obtemEstado(c.code);
  let cidades = porEstado.get(estado);
  if (!cidades) {
    cidades = [];
    porEstado.set(estado, cidades);
  }

  cidades.push(c);
});

let saida = JSON.stringify(porEstado.get("35"));
console.log(saida);
