const entrada = [
  "Acrelândia - acrelandense",
  "Assis Brasil - assis-brasiliense",
  "Brasiléia - brasileense",
  "Bujari - bujariense",
  "Capixaba - capixabense",
  "Cruzeiro do Sul - cruzeirense",
  "Epitaciolândia - epitaciolandense",
  "Feijó - feijoense",
  "Jordão - jordãoense",
  "Manoel Urbano - murbanense",
  "Marechal Thaumaturgo - thaumaturguense[2]",
  "Mâncio Lima - mâncio-limense",
  "Plácido de Castro - placidiano",
  "Porto Acre - porto-acrense",
  "Porto Walter - porto-valtense",
  "Rio Branco - rio-branquense",
  "Rodrigues Alves - rodrigues-alvense",
  "Santa Rosa do Purus - santa-rosense",
  "Sena Madureira - sena-madureirense",
  "Senador Guiomard - guiomarense",
  "Tarauacá - tarauacaense",
  "Xapuri - xapuriense",
  "Água Branca - água-branquense",
  "Anadia - anadiense",
  "Arapiraca - arapiraquense",
  "Atalaia - atalaiense",
  "Barra de Santo Antônio - barrense",
  "Barra de São Miguel - barrense",
  "Batalha - batalhense",
  "Belém - belenense",
  "Belo Monte - belo-montense",
  "Boca da Mata - bocamatense",
  "Branquinha - branquinhense",
  "Cacimbinhas - cacimbinhense",
  "Cajueiro - cajueirense",
  "Campestre - campestrense",
  "Campo Alegre - campo-alegrense",
  "Campo Grande - campo-grandense",
  "Canapi - canapiense",
  "Capela - capelense",
  "Carneiros - carneirense",
  "Chã Preta - chã-pretense",
  "Coité do Nóia - coitenense",
  "Colônia Leopoldina - leopoldinense",
  "Coqueiro Seco - coqueirense",
  "Coruripe - coruripense",
  "Craíbas - craibense",
  "Delmiro Gouveia - delmirense",
  "Dois Riachos - riachense [3]",
  "Estrela de Alagoas - estrelense",
  "Feira Grande - feira-grandense",
  "Feliz Deserto - feliz-desertense",
  "Flexeiras - flexeirense",
  "Girau do Ponciano - girauense / ponciense",
  "Ibateguara - ibateguarense",
  "Igaci - igaciense",
  "Igreja Nova - novense",
  "Inhapi - inhapiense",
  "Jacaré dos Homens - jacareense, jacarezeiro",
  "Jacuípe - jacuipense",
  "Japaratinga - japaratinguense",
  "Jaramataia - jaramataiense",
  "Jequiá da Praia - jequiense",
  "Joaquim Gomes - joaquiense [4]",
  "Jundiá - jundiaense",
  "Junqueiro - junqueirense",
  "Lagoa da Canoa - canoense",
  "Limoeiro de Anadia - limoeirense",
  "Maceió - maceioense",
  "Major Isidoro - izidorense",
  "Mar Vermelho - mar-vermelhense",
  "Maragogi - maragogiense",
  "Maravilha - maravilhense",
  "Marechal Deodoro - deodorense",
  "Maribondo - maribondense",
  "Mata Grande - mata-grandense[5]",
  "Matriz de Camaragibe - matrisense",
  "Messias - messience",
  "Minador do Negrão - minadorense",
  "Monteirópolis - monteiropolitano",
  "Murici - muriciense",
  "Novo Lino - linense",
  "Olho d'Água das Flores - olhodaguense",
  "Olho d'Água Grande - olho-grandense",
  "Olivença - oliventina ou oliventino",
  "Ouro Branco - ouro-branquense",
  "Palestina - palestinense",
  "Palmeira dos Índios - palmeirense",
  "Pão de Açúcar - pão-de-açucarense",
  "Pariconha - pariconhense",
  "Paripueira - paripueirense",
  "Passo de Camaragibe - camaragibano",
  "Paulo Jacinto - paulo-jacintense",
  "Penedo - penedense",
  "Piaçabuçu - piaçabuçuense",
  "Pilar - pilarense",
  "Pindoba - pindobense",
  "Piranhas - piranhense",
  "Poço das Trincheiras - pocense",
  "Porto Calvo - porto-calvense",
  "Porto de Pedras - porto-pedrense",
  "Porto Real do Colégio - colegiense",
  "Quebrangulo - quebrangulense",
  "Rio Largo - rio-larguense",
  "Roteiro - roteirense",
  "Santa Luzia do Norte - santaluziense ou nortense",
  "Santana do Ipanema - santanense",
  "Santana do Mundaú - mundauense",
  "São Brás - são-brasense",
  "São José da Laje - lajense",
  "São José da Tapera - taperense",
  "São Luís do Quitunde - quitundense",
  "São Miguel dos Campos - miguelense",
  "São Miguel dos Milagres - milagrense",
  "São Sebastião - são-sebastiaoense",
  "Satuba - satubense",
  "Senador Rui Palmeira - rui-palmeirense",
  "Tanque d'Arca - tanque-d'arquense",
  "Taquarana - taquaranense",
  "Teotônio Vilela - vilelano",
  "Traipu - traipuense",
  "União dos Palmares - palmarino",
  "Viçosa - viçosense",
  "Amapá - amapaense",
  "Calçoene - calçoenense",
  "Cutias - cutiense",
  "Ferreira Gomes - ferreirense",
  "Itaubal - itaubense",
  "Laranjal do Jari - laranjalense",
  "Macapá - macapaense",
  "Mazagão - mazaganense",
  "Oiapoque - oiapoquense",
  "Pedra Branca do Amapari - pedra-brancaniense",
  "Porto Grande - porto-grandense",
  "Pracuúba - pracuubense",
  "Santana - santanense",
  "Serra do Navio - serra-naviense",
  "Tartarugalzinho - tartarugalense",
  "Vitória do Jari - vitorense",
  "Alvarães - alvarense",
  "Amaturá - amaturense",
  "Anamã - anamãense",
  "Anori - anoriense",
  "Apuí - apuiense",
  "Atalaia do Norte - atalaiense",
  "Autazes - autaziense",
  "Barcelos - barcelense",
  "Barreirinha - barreirinhense",
  "Benjamin Constant - benjamin-constantense",
  "Beruri - beruriense",
  "Boa Vista do Ramos - boa-vistense",
  "Boca do Acre - bocacrense",
  "Borba - borbense",
  "Caapiranga - caapiranguese",
  "Canutama - canutamense",
  "Carauari - carauariense",
  "Careiro - careirense",
  "Careiro da Várzea - careirense-da-várzea",
  "Coari - coariense",
  "Codajás - codajaiense",
  "Eirunepé - eirunepeense [6]",
  "Envira - envirense",
  "Fonte Boa - fonte-boense",
  "Guajará - guajaraense",
  "Humaitá - humaitaense",
  "Ipixuna - ipixunaense",
  "Iranduba - irandubense",
  "Itacoatiara - itacoatiarense",
  "Itamarati - itamaratiense",
  "Itapiranga - itapiranguense",
  "Japurá - japuraense",
  "Juruá - juruaense",
  "Jutaí - jutaiense",
  "Lábrea - labreense",
  "Manacapuru - manacapuruense",
  "Manaquiri - manaquiriense",
  "Manaus - manauense, manauara",
  "Manicoré - bacurau",
  "Maraã - maraaense",
  "Maués - maueense, mauesense",
  "Nhamundá - nhamundaense",
  "Nova Olinda do Norte - nova-olindense",
  "Novo Airão - novo-airense; novo-airãoense",
  "Novo Aripuanã - aripuanense; novo-aripuanense",
  "Parintins - parintinense",
  "Pauini - pauiniense",
  "Presidente Figueiredo - figueirense",
  "Rio Preto da Eva - rio-pretense",
  "Santa Isabel do Rio Negro - santa-isabelense",
  "Santo Antônio do Içá - içaense [7]",
  "São Gabriel da Cachoeira - são-gabrielense",
  "São Paulo de Olivença - paulivense",
  "São Sebastião do Uatumã - uatumãense",
  "Silves - silvense, saracaense",
  "Tabatinga - tabatinguense",
  "Tapauá - tapauense",
  "Tefé - tefeense [8]",
  "Tonantins - tonantinense",
  "Uarini - uariniense; uarinense",
  "Urucará - urucaraense",
  "Urucurituba - urucuritubense",
  "Afonso Cláudio - afonso-claudense",
  "Água Doce do Norte - água-docense",
  "Águia Branca - aguiabranquense",
  "Alegre - alegrense",
  "Alfredo Chaves - alfredense",
  "Alto Rio Novo - alto-rio-novense",
  "Anchieta - anchietense",
  "Apiacá - apiacaense",
  "Aracruz - aracruzense",
  "Atílio Vivácqua - atiliense",
  "Baixo Guandu - guanduense",
  "Barra de São Francisco - francisquense",
  "Boa Esperança - esperancense",
  "Bom Jesus do Norte - bom-jesuense",
  "Brejetuba - brejetubense",
  "Cachoeiro de Itapemirim - cachoeirense",
  "Cariacica - cariaciquense",
  "Castelo - castelense",
  "Colatina - colatinense",
  "Conceição da Barra - barrense",
  "Conceição do Castelo - conceiçoense",
  "Divino de São Lourenço - divinense",
  "Domingos Martins - martinense",
  "Dores do Rio Preto - riopretense",
  "Ecoporanga - ecoporanguense",
  "Fundão - fundoense",
  "Governador Lindenberg - lindenberguense",
  "Guaçuí - guaçuiense",
  "Guarapari - guarapariense",
  "Ibatiba - ibatibense",
  "Ibiraçu - ibiraçuense",
  "Ibitirama - ibitiramense",
  "Iconha - iconhense",
  "Irupi - irupiense",
  "Itaguaçu - itaguaçuense",
  "Itapemirim - itapemirinense",
  "Itarana - itaranense",
  "Iúna - iunense",
  "Jaguaré - jaguarense",
  "Jerônimo Monteiro - jeronimense",
  "João Neiva - joão-neivense",
  "Laranja da Terra - laranjense",
  "Linhares - linharense",
  "Mantenópolis - mantenopolitano",
  "Marataízes - marataizense",
  "Marechal Floriano - florianense",
  "Marilândia - marilandense",
  "Mimoso do Sul - mimosense",
  "Montanha - montanhense",
  "Mucurici - mucuriciense",
  "Muniz Freire - munizfreirense",
  "Muqui - muquiense",
  "Nova Venécia - veneciano",
  "Pancas - panquense",
  "Pedro Canário - canariense",
  "Pinheiros - pinheirense",
  "Piúma - piumense",
  "Ponto Belo - pontobelense",
  "Presidente Kennedy - kennedense",
  "Rio Bananal - ribanense",
  "Rio Novo do Sul - sulrionovense",
  "Santa Leopoldina - leopoldinense",
  "Santa Maria de Jetibá - santa-mariense",
  "Santa Teresa - teresense",
  "São Domingos do Norte - dominguense",
  "São Gabriel da Palha - gabrielense",
  "São José do Calçado - calçadense",
  "São Mateus - mateense",
  "São Roque do Canaã - são roquense",
  "Serra - serrano",
  "Sooretama - sooretamense",
  "Vargem Alta - vargem-altense",
  "Venda Nova do Imigrante - venda-novense",
  "Viana - vianense",
  "Vila Pavão - pavoense",
  "Vila Valério - vila-valeriense",
  "Vila Velha - vila-velhense, canela-verde",
  "Vitória - vitoriense",
  "Abadia de Goiás - abadiense",
  "Abadiânia - abadiense",
  "Acreúna - acreunense",
  "Adelândia - adelandense",
  "Água Fria de Goiás - água-friense",
  "Água Limpa - água-limpense",
  "Águas Lindas de Goiás - águas-lindense",
  "Alexânia - alexaniense",
  "Aloândia - aloandense",
  "Alto Horizonte - alto horizontino",
  "Alto Paraíso de Goiás - alto-paraisense",
  "Alvorada do Norte - alvoradense-do-norte",
  "Amaralina - amaralinense",
  "Americano do Brasil - americanense-do-brasil",
  "Amorinópolis - amorinopolino",
  "Anápolis - anapolitano, anapolino, anapolense",
  "Anhanguera - anhanguerino",
  "Anicuns - anicuense",
  "Aparecida de Goiânia - aparecidense",
  "Aparecida do Rio Doce - rio-docense",
  "Aporé - aporeense",
  "Araçu - araçuense",
  "Aragoiânia - aragoiano",
  "Araguapaz - araguapaense",
  "Arenópolis - arenopolino",
  "Aruanã - aruanuense",
  "Aurilândia - aurilandense",
  "Avelinópolis - avelinopolino",
  "Baliza - balizense",
  "Barro Alto - barroaltense",
  "Bela Vista de Goiás - bela-vistense",
  "Bom Jardim de Goiás - bom-jardinense",
  "Bom Jesus de Goiás - bom-jesuense",
  "Bonfinópolis - bonfinopolino",
  "Bonópolis - bonopolino",
  "Brazabrantes - brazabrantino",
  "Britânia - britaniense",
  "Buriti Alegre - buriti-alegrense",
  "Buriti de Goiás - buritiense",
  "Buritinópolis - buritinopolense",
  "Cabeceiras - cabeceirense",
  "Cachoeira Alta - cachoeiraltense",
  "Cachoeira de Goiás - cachoeirense",
  "Cachoeira Dourada - cachoeirense-do-sul",
  "Caçu - caçuense",
  "Caiapônia - caiaponiense",
  "Caldas Novas - caldas-novense",
  "Caldazinha - caldazinhense",
  "Campestre de Goiás - campestrino",
  "Campinaçu - campinaçuense",
  "Campinorte - campinortense",
  "Campo Alegre de Goiás - campoalegrense",
  "Campo Limpo de Goiás - campolimpense",
  "Campos Belos - campo-belense",
  "Campos Verdes - campo-verdense",
  "Carmo do Rio Verde - carmo-rio-verdino",
  "Castelândia - castelandense",
  "Catalão - catalano",
  "Caturaí - caturaiense",
  "Cavalcante - cavalcantense",
  "Ceres - ceresino",
  "Cezarina - cezarinense",
  "Chapadão do Céu - ceúchapadense",
  "Cidade Ocidental - ocidentalense",
  "Cocalzinho de Goiás - cocalzinhense",
  "Colinas do Sul - colinense",
  "Córrego do Ouro - corregorino",
  "Corumbá de Goiás - corumbaense",
  "Corumbaíba - corumbaibense",
  "Cristalina - cristalinense",
  "Cristianópolis - cristianopolino",
  "Crixás - crixaense",
  "Cromínia - crominiense",
  "Cumari - cumarino",
  "Damianópolis - damianopolino",
  "Damolândia - damolandense",
  "Davinópolis - davinopolino",
  "Diorama - dioramense",
  "Divinópolis de Goiás - divinopolino",
  "Doverlândia - doverlandense",
  "Edealina - edealinense",
  "Edéia - edeense",
  "Estrela do Norte - estrela-nortense",
  "Faina - fainense",
  "Fazenda Nova - fazenda-novense ou fazendeiro-novense",
  "Firminópolis - firminopolino",
  "Flores de Goiás - florense",
  "Formosa - formosense",
  "Formoso - formosense",
  "Gameleira de Goiás - gameleirense",
  "Goianápolis - goianapolino",
  "Goiandira - goiandirense",
  "Goianésia - goianesiense",
  "Goiânia - goianiense",
  "Goiás - Vilaboense ou goiano [10]",
  "Goianira - goianirense",
  "Goiatuba - goiatubense",
  "Gouvelândia - gouvelandense",
  "Guapó - guapoense",
  "Guaraíta - guaraitense",
  "Guarani de Goiás - guaraniense",
  "Guarinos - guarinense",
  "Heitoraí - heitoraiense",
  "Hidrolândia - hidrolandense",
  "Hidrolina - hidrolinense",
  "Iaciara - iaciarense",
  "Inaciolândia - inaciolandense",
  "Indiara - indiarense",
  "Inhumas - inhumense",
  "Ipameri - ipamerino",
  "Ipiranga de Goiás - ipiranguense",
  "Iporá - iporaense",
  "Israelândia - israelandense",
  "Itaberaí - itaberino",
  "Itaguari - itaguarino",
  "Itaguaru - itaguaruense",
  "Itajá - itajaense",
  "Itapaci - itapacino",
  "Itapirapuã - itapirapuano",
  "Itapuranga - itapuranguense",
  "Itarumã - itarumaense",
  "Itauçu - itauçuense",
  "Itumbiara - itumbiarense",
  "Ivolândia - ivolandense",
  "Jandaia - jandaiense",
  "Jaraguá - jaraguense",
  "Jataí - jataiense",
  "Jaupaci - jaupaciense",
  "Jesúpolis - jesupolino",
  "Joviânia - jovianiense",
  "Jussara - jussarense",
  "Lagoa Santa - lagoa-santense",
  "Leopoldo de Bulhões - leopoldense",
  "Luziânia - luzianiense",
  "Mairipotaba - mairipotabense",
  "Mambaí - mambaiense",
  "Mara Rosa - mararrosense",
  "Marzagão - marzagonense",
  "Matrinchã - matrinchãense",
  "Maurilândia - maurilandense",
  "Mimoso de Goiás - mimosense",
  "Minaçu - minaçuense",
  "Mineiros - mineirense",
  "Moiporá - moiporaense",
  "Monte Alegre de Goiás - monte-alegrense",
  "Montes Claros de Goiás - montesclarense de goiás",
  "Montividiu - montividiuense",
  "Montividiu do Norte - montividense",
  "Morrinhos - morrinhense",
  "Morro Agudo de Goiás - morroagudense",
  "Mossâmedes - mossamedino",
  "Mozarlândia - mozarlandense",
  "Mundo Novo - mundo-novense",
  "Mutunópolis - mutunopolitano",
  "Nazário - nazarinense",
  "Niquelândia - niquelandense",
  "Nova América - novo-americano",
  "Nova Aurora - nova-aurorense",
  "Nova Crixás - nova-crixaense",
  "Nova Glória - nova-glorino",
  "Nova Iguaçu de Goiás - nova iguaçuense",
  "Nova Roma - nova-romano",
  "Nova Veneza - nova-venezino",
  "Novo Brasil - novo-brasiliense",
  "Novo Gama - novo-gamense",
  "Novo Planalto - planaltense",
  "Orizona - orizonense",
  "Ouro Verde de Goiás - ouroverdense",
  "Ouvidor - ouvidorense",
  "Padre Bernardo - padre-bernardense",
  "Palestina de Goiás - palestinense",
  "Palmeiras de Goiás - palmeirenses",
  "Palmelo - palmario",
  "Palminópolis - palminopolino",
  "Panamá - panamaense",
  "Paranaiguara - paranaiguaro",
  "Paraúna - paraunense",
  "Perolândia - perolandense",
  "Petrolina de Goiás - petrolinense",
  "Pilar de Goiás - pilarense",
  "Piracanjuba - piracanjubense",
  "Piranhas - piranhense",
  "Pirenópolis - pirenopolino",
  "Pires do Rio - piresino",
  "Planaltina - planaltinense",
  "Pontalina - pontalinense",
  "Porangatu - porangatuense",
  "Porangatu - porangatuense",
  "Porteirão - porteirense",
  "Portelândia - portelandense",
  "Posse - possense",
  "Professor Jamil - jamilense",
  "Quirinópolis - quirinopolino",
  "Rialma - rialmense",
  "Rianápolis - rianapolino",
  "Rio Quente - rio-quentense",
  "Rio Verde - rio-verdense",
  "Rubiataba - rubiatabense",
  "Sanclerlândia - sanclerlandense",
  "Santa Bárbara de Goiás - santabarbarense",
  "Santa Cruz de Goiás - santacruzano",
  "Santa Fé de Goiás - santa-feense",
  "Santa Helena de Goiás - santa-helenense [11][12]",
  "Santa Isabel - santa-isabelense",
  "Santa Rita do Araguaia - santarritense",
  "Santa Rita do Novo Destino - santarritense",
  "Santa Rosa de Goiás - santarosense",
  "Santa Tereza de Goiás - santerezense",
  "Santa Terezinha de Goiás - teresinhense",
  "Santo Antônio da Barra - santoantoniense",
  "Santo Antônio de Goiás - santoantoniense",
  "Santo Antônio do Descoberto - santo antôniensse",
  "São Domingos - dominicano",
  "São Francisco de Goiás - franciscano",
  "São João da Paraúna - são-joanense",
  "São João d'Aliança - são-joanense",
  "São Luís de Montes Belos - monte-belense",
  "São Luiz do Norte - são-luizense",
  "São Miguel do Araguaia - sãomiguelense",
  "São Miguel do Passa Quatro - passaquatrense",
  "São Patrício - sampatriciense",
  "São Simão - simonense",
  "Senador Canedo - canedense",
  "Serranópolis - serranopolino",
  "Silvânia - silvaniense",
  "Simolândia - simolandense",
  "Sítio d'Abadia - sitiense",
  "Taquaral de Goiás - taquaralense",
  "Teresina de Goiás - teresinense",
  "Terezópolis de Goiás - terezopolino",
  "Três Ranchos - trirranchense",
  "Trindade - trindadense",
  "Trombas - trombense",
  "Turvânia - turvâniense",
  "Turvelândia - turvelandense",
  "Uirapuru - uirapuruense",
  "Uruaçu - uruaçuense",
  "Uruana - uruanense",
  "Urutaí - urutaíno",
  "Valparaíso de Goiás - valparaisense",
  "Varjão - varjãoense",
  "Vianópolis - vianopolino",
  "Vicentinópolis - vicentinopolino",
  "Vila Boa - vila-boense",
  "Vila Propício - propiciano",
  "Açailândia - açailandense",
  "Bacabal - bacabalense",
  "Balsas - balsense",
  "Barra do Corda - barra-cordense",
  "Barreirinhas - barreirinhense",
  "Caxias - caxiense",
  "Grajaú - grajauense",
  "Graça Aranha - gracense",
  "Guimarães - guimarense, vimarense",
  "Humberto de Campos - humbertuense",
  "Imperatriz - imperatrizense",
  "Itapecuru Mirim - itapecuruense",
  "Joselândia - joselandense",
  "Loreto - loretense",
  "Miranda do Norte - mirandense",
  "Nova Iorque - nova-iorquense",
  "Paço do Lumiar - luminense",
  "Passagem Franca - passagense",
  "Pinheiro - pinheirense",
  "Pio XII - pio-docense, pio-dozense",
  "Poção de Pedras - poção-pedrense",
  "Presidente Vargas - presidentino, presidente-varguense",
  "Rosário - rosariense",
  "Riachão - riachoense, riachãoense",
  "Santa Inês - santa-inesense",
  "São João do Caru - são-joanense, caruense",
  "São João dos Patos - patoense",
  "São Luís - ludovicente, são-luisense",
  "São Pedro da Água Branca - são-pedrense",
  "Timon - timonense",
  "Vargem Grande - vargem-grandense",
  "Zé Doca - zé-doquense",
  "Acorizal - acorizalense",
  "Água Boa - água-boense",
  "Alta Floresta - alta-florestense; florestense",
  "Alto Araguaia - alto-araguaiense",
  "Alto Boa Vista - alto-boa-vistense",
  "Alto Garças - alto-garcense",
  "Alto Paraguai - alto-paraguaiense",
  "Alto Taquari - taquariense",
  "Apiacás - apiacaense",
  "Araguaiana - araguaianense",
  "Araguainha - araguainhense",
  "Araputanga - araputanguense",
  "Arenápolis - arenapolitano",
  "Aripuanã - aripuanense",
  "Barra do Bugres - barra-bugrense",
  "Barra do Garças - barra-garcense",
  "Bom Jesus do Araguaia - bom-jesusense-do-araguaia",
  "Brasnorte - brasnortense",
  "Cáceres - cacerense",
  "Canarana - canaranense",
  "Campo Novo do Parecis - camponovense",
  "Campo Verde - campo-verdense",
  "Chapada dos Guimarães - chapadense",
  "Colíder - Colidense",
  "Cuiabá - cuiabano",
  "Lucas do Rio Verde - luverdense",
  "Nobres - nobrense",
  "Nova Mutum - mutuense",
  "Novo Horizonte do Norte - novo-horizontino",
  "Paranatinga - paranatinguense",
  "Pontes e Lacerda - pontes-lacerdense",
  "Primavera do Leste - primaverense",
  "Rondonópolis - rondonopolitano",
  "Santo Antônio do Leverger - levergense; santo-antoniense",
  "Sinop - sinopense",
  "Sorriso - sorrisiense",
  "Tangará da Serra - tangaraense",
  "Várzea Grande - várzea-grandense",
  "Araripina - araripinense",
  "Afogados da Ingazeira - afogadense",
  "Arcoverde - arco-verdense",
  "Belo Jardim - belojardinense",
  "Bom Jardim - bom-jardinense",
  "Cabo de Santo Agostinho - cabense",
  "Camaragibe - camaragibense[13]",
  "Camocim de São Félix - camociense",
  "Caruaru - caruaruense",
  "Escada - escadense",
  "Garanhuns - garanhuense",
  "Gravatá - gravataense",
  "Ipojuca - ipojuquense",
  "Itaíba - itaibense",
  "Jaboatão dos Guararapes - jaboatonense",
  "Limoeiro - limoeirense",
  "Moreno - morenense",
  "Olinda - olindense",
  "Paulista - paulistense",
  "Pesqueira - pesqueirense",
  "Petrolina - petrolinense",
  "Recife - recifense",
  "Salgueiro - salgueirense",
  "Santa Cruz do Capibaribe - santa-cruzense",
  "São Vicente Férrer - vicentino",
  "Serra Talhada - serra-talhadense",
  "Tabira - tabirense",
  "Xexéu - xexeuense",
  "Água Branca - água-branquense",
  "Alto Longá - alto-longaense",
  "Altos - altoense",
  "Amarante - amarantino",
  "Cajazeiras do Piauí - cajazerense",
  "Canto do Buriti - canto-buritiense",
  "Curimatá - curimataense",
  "José de Freitas - josé-freitense",
  "Luís Correia - luís-correiense",
  "Manoel Emídio - manoel-emidiano",
  "Monsenhor Gil - monsenhor-gilense",
  "Novo Oriente do Piauí - novorientino, orientense",
  "Parnaíba - parnaibano",
  "Picos - picoense",
  "Redenção do Gurgueia - redençoense",
  "Regeneração - regenerense",
  "São João do Piauí - são-joanense",
  "São Pedro do Piauí - são-pedrense",
  "São Raimundo Nonato - são-raimundense",
  "Oeiras - oeirense",
  "Teresina - teresinense",
  "Uruçuí - uruçuiense",
  "Areia Branca - areia-branquense",
  "Caicó - caicoense",
  "Ceará-Mirim - ceará-mirinense",
  "Extremoz - extremozense",
  "Jardim de Angicos - jardinense",
  "João Câmara - camaraense",
  "Macaíba - macaibense",
  "Martins - martinense",
  "Mossoró - mossoroense",
  "Natal - natalense",
  "Nísia Floresta - nísia-florestense",
  "Nova Cruz - nova-cruzense",
  "Paraú - parauense",
  "Parnamirim - parnamirinense",
  "Passa e Fica - passa-fiquense",
  "Pau dos Ferros - pau-ferrense",
  "Sítio Novo - sítio-novense",
  "Umarizal - umarizalense",
  "Upanema - upanemense",
  "Ariquemes - ariquemense",
  "Cacoal - cacoalense",
  "Espigão d'Oeste - espigoense",
  "Governador Jorge Teixeira - jorge-teixerense",
  "Guajará-Mirim - guajara-mirense",
  "Jaru - jaruense",
  "Ji-Paraná - ji-paranaense",
  "Ouro Preto do Oeste - ouro-pretense",
  "Pimenta Bueno - pimentense",
  "Porto Velho - porto-velhense",
  "Rolim de Moura - rolim-mourense",
  "São Miguel do Guaporé - miguelense",
  "Theobroma - theobromense [15]",
  "Vilhena - vilhenense",
  "Alto Alegre - alto-alegrense",
  "Amajari - amajariense",
  "Boa Vista - boa-vistense",
  "Caracaraí - caracaraiense",
  "Caroebe - caroebense",
  "Normandia - normandiense",
  "Pacaraima - pacaraimense",
  "Agrolândia - agrolandense",
  "Alfredo Wagner - alfredense",
  "Arabutã - arabutanense",
  "Araquari - araquariense",
  "Araranguá - araranguaense",
  "Armazém - armazenense",
  "Ascurra - ascurrense",
  "Balneário Arroio do Silva - arroiense; arroio-silvense",
  "Balneário Camboriú - balneocamboriuense",
  "Balneário Gaivota - gaivotense",
  "Barra Velha - barra-velhense",
  "Biguaçu - biguaçuense",
  "Blumenau - blumenauense",
  "Braço do Norte - braço-nortense",
  "Brusque - brusquense",
  "Caçador - caçadorense",
  "Calmon - calmonense",
  "Camboriú - camboriuense",
  "Campo Belo do Sul - campo-belense",
  "Campo Erê - campo-erense",
  "Canoinhas - canoinhense",
  "Capão Alto - capão-altense",
  "Capinzal - capinzalense",
  "Capivari de Baixo - capivariense",
  "Celso Ramos - celso-ramense",
  "Chapecó - chapecoense",
  "Cocal do Sul - sul-cocalense",
  "Concórdia - concordiense",
  "Correia Pinto - correia-pintense",
  "Criciúma - criciumense",
  "Ermo - ermense",
  "Erval Velho - ervalense",
  "Florianópolis - florianopolitano",
  "Forquilhinha - forquilhinhense",
  "Fraiburgo - fraiburguense",
  "Gaspar - gasparense",
  "Governador Celso Ramos - gancheiro",
  "Grão-Pará - grão-paraense",
  "Gravatal - gravatalense [16][17]",
  "Içara - içarense",
  "Ilhota - ilhotense",
  "Imbituba - imbitubense",
  "Indaial - indaialense",
  "Ipumirim - ipumirinense",
  "Itajaí - itajaiense",
  "Jacinto Machado - jacinto-machadense",
  "Jaguaruna - jaguarunense",
  "Jaraguá do Sul - jaraguaense",
  "Joaçaba - joaçabense",
  "Joinville - joinvilense",
  "Lages - lageano[18]",
  "Laguna - lagunense",
  "Lebon Régis - lebonregense",
  "Lontras - lontrense",
  "Massaranduba - massarandubense",
  "Morro da Fumaça - fumacense",
  "Orleans - orleanense",
  "Palhoça - palhocense",
  "Passo de Torres - passo-torrense",
  "Ponte Alta - ponte-altense",
  "Ponte Alta do Norte - norte-ponte-altense",
  "Porto União - porto-unionense [20]",
  "Praia Grande - praia-grandense",
  "Presidente Getúlio - getuliense",
  "Rio do Sul - rio-sulense",
  "Rio Fortuna - rio-fortunense",
  "Rodeio - rodeense",
  "Santa Rosa de Lima - santa-rosa-limense",
  "Santo Amaro da Imperatriz - santoamarense",
  "São Bonifácio - são-bonifacense",
  "São José - josefense",
  "Siderópolis - sideropolitano",
  "Sombrio - sombriense",
  "Taió - taioense",
  "Tangará - tangaraense",
  "Timbó - timboense",
  "Treze de Maio - treze-maiense",
  "Tubarão - tubaronense",
  "Turvo - turvense",
  "Urussanga - urussanguense [21]",
  "Videira - videirense",
  "Xanxerê - xanxerense",
  "Aracaju - aracajuano, aracajuense",
  "Estância - estanciano",
  "Itabaiana - itabaianense",
  "Itaporanga d'Ajuda - itaporanguense",
  "Japoatã - japoatãense",
  "Lagarto - lagartense",
  "Laranjeiras - laranjeirense",
  "Neópolis - neopolitano",
  "Nossa Senhora das Dores - dorense",
  "Simão Dias - simão-diense",
  "Abreulândia - abreulandense",
  "Aguiarnópolis - aguiarnopolense",
  "Aliança do Tocantins - aliancense",
  "Almas - almense",
  "Alvorada - alvoradense",
  "Ananás - ananaense",
  "Angico - angicoense [22]",
  "Aparecida do Rio Negro - aparecidense",
  "Aragominas - aragominense",
  "Araguacema - araguacemense",
  "Araguaçu - araguaçuense",
  "Araguaína - araguainense",
  "Araguanã - araguanãense",
  "Araguatins - araguatinense",
  "Arapoema - arapoemense",
  "Arraias - arraiano",
  "Augustinópolis - augustinopolino",
  "Aurora do Tocantins - aurorense",
  "Axixá do Tocantins - axixaense",
  "Darcinópolis - darcinopolino,",
  "Dianópolis - dianopolino, dianopolitano",
  "Divinópolis do Tocantins - divinopolino, divinopolitano",
  "Dois Irmãos do Tocantins - dois-irmanense",
  "Dueré - duereense",
  "Esperantina - esperantinense",
  "Fátima - fatimense",
  "Figueirópolis - figueiropolense, figueiropolino",
  "Filadélfia - filadelfiense",
  "Formoso do Araguaia - formosense",
  "Gurupi - gurupiense",
  "Itacajá - itacajense",
  "Miracema do Tocantins - miracemense",
  "Palmas - palmense",
  "Palmeirópolis - palmeiropolitano",
  "Paraíso do Tocantins - paraisense",
  "Pedro Afonso - pedro-afonsino",
  "Porto Nacional - portuense",
  "Taguatinga - taguatinguense",
];

const gentilicos = entrada.map((e) => e.split(" - "));

const fs = require("fs");

// Carregar
const conteudo = fs.readFileSync("../base/municipios.json", "utf-8");
const municipios = JSON.parse(conteudo);

let contador = 0;
let duplicata = 0;

// gentilicos.forEach((g) => {
//   let encontrado = municipios.filter((m) => m.nome === g[0]);
//   if (encontrado && encontrado.length > 0) {
//     if (encontrado.length == 1) {
//       contador++;
//     } else {
//       duplicata++;
//       console.log("Duplicado em", g[0]);
//     }
//   } else {
//     console.log("Busca", g);
//   }
// });

// console.log("Encontrados", contador);
// console.log("Duplicados ou mais", duplicata);

function gentilicoDe(m) {
  let encontrado = gentilicos.find((g) => g[0] === m);
  if (encontrado) {
    return encontrado[1];
  }

  return "";
}

function removeDigitoVerificador(codigo) {
  return Math.floor(codigo / 10);
}

function toConcept(m) {
  return {
    code: removeDigitoVerificador(m.ibge),
    display: m.nome,
    property: [
      {
        code: "type",
        valueCode: "city",
      },
      {
        code: "ethnical",
        valueString: gentilicoDe(m.nome),
      },
    ],
  };
}

function obtemEstado(ibge) {
  return ibge.toString().substring(0, 2);
}

let conceitos = municipios.map((m) => toConcept(m));
let porEstado = new Map();

conceitos.forEach((c) => {
  let estado = obtemEstado(c.code);
  let cidades = porEstado.get(estado);
  if (!cidades) {
    cidades = [];
    porEstado.set(estado, cidades);
  }

  cidades.push(c);
});

let saida = JSON.stringify(porEstado.get("34"));
console.log(saida);
